SD of temporary entitities and parameters updated
ostis-ai/ostis-standard pull request #240
Opened 2022-02-09 12:43 UTC by ShunkevichDV

2022-02-24 20:58 UTC, NikitaZotov requested changes

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_parameters_and_quantities.tex
> +\scnexplanation{Связки отношения \textit{соединение значений ориентированного параметра*} связывают связки отношения \textit{порядок величин*} и величину (возможно, интервальную) того же параметра, э
```suggestion
\scnexplanation{Связки отношения \textit{соединение значений ориентированного параметра*} связывают связки отношения \textit{порядок величин*} и величину (возможно, интервальную) того же параметра, элементами которой являются все сущности, значение данного параметра для которых лежит в интервале, для которого границы задаются величинами, являющимися компонентами указанной связки отношения \textit{порядок величин*}.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +			\scnidtf{временная сущность, длительность которой в данном контексте считается несущественной (пренебрежительно малой)}
```suggestion
			\scnidtf{временная сущность, длительность существования которой в данном контексте считается несущественной (пренебрежительно малой)}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +	\scnnote{Следует отметить, что приведенная классификация \textit{временных сущностей} характеризует не столько сами \textit{временные сущности}, сколько наши знания о них и степень детализации знани
```suggestion
	\scnnote{Следует отметить, что приведенная классификация \textit{временных сущностей} характеризует не столько сами \textit{временные сущности}, сколько наши знания о них и степень детализации знаний об этих сущностях, с которой они описаны в базе знаний. Так, если для решения конкретных задач не важно, как изменялась некоторая \textit{временная сущность} в рамках какого-либо периода времени, а важно только ее начальное и конечное состояние, то она может рассматриваться как \textit{точечная временная сущность}. Впоследствии та же \textit{временная сущность} может быть рассмотрена и описана с большей степенью детализации, и таким образом, уже не будет точечной.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +При этом следует помнить, что сам \textit{процесс} как уточнение динамики некоторой последовательности ситуаций и событий, также является сущностью, принадлежащей к классу \textit{временных сущностей
```suggestion
\scnnote{Следует отличать, например, \textit{материальную сущность} (некоторый физический или, в частности, биологический объект) от различных динамических структур (\textit{процессов}), которые с той или иной степенью детализации и в том или ином ракурсе отражают (описывают) динамику изменений этой \textit{материальной сущности}. 

Сам \textit{процесс} как уточнение динамики некоторой последовательности ситуаций и событий, также является сущностью, принадлежащей к классу \textit{временных сущностей}.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnnote{Поскольку \textit{процесс} представляет собой изменяющуюся во времени динамическую структуру, то полностью представить процесс в базе знаний в общем случае не представляется возможным. Однак
```suggestion
\scnnote{Поскольку \textit{процесс} представляет собой изменяющуюся во времени динамическую структуру, то полностью представить процесс в базе знаний в общем случае не представляется возможным. Однако, можно ввести sc-элемент, обозначающий конкретный процесс, с необходимой степенью детализации описать его декомпозицию на более частные подпроцессы или/и описать ситуации, соответствующие состояниям процесса в разные моменты времени. В данном случае можно провести некоторую аналогию с \textit{бесконечными множествами}, все элементы которых физически не могут быть представлены в базе знаний одновременно, тем не менее, само множество и некоторые из его элементов могут быть описаны с необходимой степенью детализации.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{процесс, длительность которого в данном контексте считается несущественной (пренебрежимо малой)}
```suggestion
\scnidtf{процесс, длительность существования которого в данном контексте считается несущественной (пренебрежимо малой)}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{точечная временная сущность, являющаяся началом и/или завершением какой-либо временной сущности, например, процесса}
```suggestion
\scnidtf{точечная временная сущность, являющаяся началом и/или завершением какой-либо временной сущности (например, процесса)}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{сразу позже*}
Возможно будет лучше "чуть позже" или "незадолго до"

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +	\scnnote{Некоторые значения параметра одновременность могут быть подмножествами других значений того же параметра. С семантической точки зрения такая взаимосвязь будет означать, что первое из указан
```suggestion
	\scnnote{Некоторые значения параметра одновременности могут быть подмножествами других значений того же параметра. С семантической точки зрения такая взаимосвязь будет означать, что первое из указанных значений описывает \textit{одновременность} \textit{временных сущностей} с большей точностью. Так, в приведенном примере величина ``\textit{2002 год}'' описывает одновременность временных сущностей с точностью до года, а величина ``\textit{июль 2022 года}'' описывает одновременность временных сущностей с точностью до месяца. При этом очевидно, что сущности, входящие во величину ``\textit{июль 2022 года}'' будут также входить и в величину ``\textit{2022 год}'' (как например временная сущность $\bm{sk})$. В приведенном примере для простоты предполагается, что все измерения производятся по Григорианскому календарю.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +	\scnnote{Некоторые значения параметра одновременность могут быть подмножествами других значений того же параметра. С семантической точки зрения такая взаимосвязь будет означать, что первое из указан
```suggestion
	\scnnote{Некоторые значения параметра одновременность могут быть подмножествами других значений того же параметра. Семантика такой взаимосвязи будет указывать на то, что первое из указанных значений описывает \textit{одновременность} \textit{временных сущностей} с большей точностью. Так, в приведенном примере величина ``\textit{2002 год}'' описывает одновременность временных сущностей с точностью до года, а величина ``\textit{июль 2022 года}'' описывает одновременность временных сущностей с точностью до месяца. При этом очевидно, что сущности, входящие во величину ``\textit{июль 2022 года}'', будут также входить и в величину ``\textit{2022 год}'' (как например временная сущность $\bm{sk})$. В приведенном примере для простоты предполагается, что все измерения производятся по Григорианскому календарю.}
```

2022-02-24 20:58 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities_kb.tex
> +\scnidtf{процесс, длительность которого в данном контексте считается несущественной (пренебрежимо малой)}
Вроде это было выше

2022-02-27 16:19 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_parameters_and_quantities.tex
> +\scnexplanation{Связки отношения \textit{соединение значений ориентированного параметра*} связывают связки отношения \textit{порядок величин*} и величину (возможно, интервальную) того же параметра, э
мне кажется "границы интервала" звучит правильнее, чем "границы для интервала"

2022-02-27 16:21 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +	\scnnote{Следует отметить, что приведенная классификация \textit{временных сущностей} характеризует не столько сами \textit{временные сущности}, сколько наши знания о них и степень детализации знани
"же та же" звучит очень плохо

2022-02-27 16:23 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{сразу позже*}
имеется в виду, что одна сущность начинается сразу после другой, "чуть позже" и тем более "незадолго до" это другое

2022-02-27 16:26 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +При этом следует помнить, что сам \textit{процесс} как уточнение динамики некоторой последовательности ситуаций и событий, также является сущностью, принадлежащей к классу \textit{временных сущностей
Предлагаю средний вариант "При этом сам процесс..."

2022-02-27 16:34 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities_kb.tex
> +\scnidtf{процесс, длительность которого в данном контексте считается несущественной (пренебрежимо малой)}
Специально вынесено еще и сюда, аналогичные ситуации есть и в других местах, чтобы показать, что одни и те же сущности исследуются в разных ПрО

2022-02-27 16:46 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +	\scnnote{Некоторые значения параметра одновременность могут быть подмножествами других значений того же параметра. С семантической точки зрения такая взаимосвязь будет означать, что первое из указан
Семантика не может указывать, предложил другой вариант

2022-02-27 17:09 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_parameters_and_quantities.tex
> +\scnexplanation{Связки отношения \textit{соединение значений ориентированного параметра*} связывают связки отношения \textit{порядок величин*} и величину (возможно, интервальную) того же параметра, э
Я подумал, что повтор местоимения который делает предложение менее понятным, когда начинаешь его читать. Возможно, стоит использовать "чьи"?

2022-02-27 17:11 UTC, NikitaZotov commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{сразу позже*}
"Сразу позже" выглядит как жаргонизм

2022-02-27 17:13 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_parameters_and_quantities.tex
> +\scnexplanation{Связки отношения \textit{соединение значений ориентированного параметра*} связывают связки отношения \textit{порядок величин*} и величину (возможно, интервальную) того же параметра, э
тоже не очень. Не совсем понял насчет местоимения, слово "который" же в разных родах используется здесь, ничему не мешает вроде

2022-02-27 17:15 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_sys_models/sd_kb/sd_temp_entities.tex
> +\scnidtf{сразу позже*}
да я бы не сказал, ну можно сделать "непосредственно позже*"

2022-02-27 19:38 UTC, NikitaZotov approved these changes

2022-02-27 19:47 UTC, merged