Entered a snippet General structure of the Standard
ostis-ai/ostis-standard pull request #252
Opened 2022-04-22 10:51 UTC by ElizavetaLukomskaya

2022-05-05 10:40 UTC, ShunkevichDV requested changes
1. Файл common_standart_structure перенести в Contents и подключить в beginning.tex после вот этого:

\input{Contents/title_part_2022}
\newpage

Должно получиться 

\input{Contents/title_part_2022}
\newpage

\input{Contents/common_standart_structure}
\newpage

2. Файл title_part_common не менялся, не нужно создавать его копию, папку OSTIS standard убираем целиком

3. См. комментарии по тексту

2022-05-05 20:07 UTC, ElizavetaLukomskaya reviewed
1. Добавила файл в beginning.tex
2. Убрала папку OSTIS standard
3. Файл title_part_common.tex оставила нетронутым

2022-05-05 21:25 UTC, ShunkevichDV requested changes

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +	\scnaddlevel{1}
Лишний уровень

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +			Данная часть \textit{Стандарта OSTIS} начинается с \textit{раздела} "Предметная область и онтология кибернетических систем"{} и заканчивается \textit{разделом} "Предметная область и онтология логи
Кавычки нужны именно `` '', если мы выделяем имя какой-то сущности. Зеленый цвет означает жирный курсив

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +					\scntext{часть}{описание онтологических моделей естественно-языковых \textit{интерфейсов интеллектуальных компьютерных систем}, а также методов и средств их проектирования}.
Внутри файла не поддерживается формальный текст, давайте сделаем "их проектирования, включая описание онтологических моделей..."

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +					\item методов производства(реализации) \textit{ostis-систем};
пробел перед скобкой

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +					\item описание "нейросетевых"{} моделей обработки \textit{знаний}, а также методов и средств их проектирования;
тут кавычки правильные, если что, менять не нужно

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +			\scnidtf{Предметная область и онтология Экосистемы компьютерных систем, построенных на \textit{Технологии OSTIS}}
Не нужно дополнительный идентификатор, просто уберите

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +			\item Библиография \textit{Стандарта OSTIS}
Все три слова жирный курсив

2022-05-05 21:25 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +			Эта часть \textit{Стандарта OSTIS} представлена \textit{разделом} "Предметная область и онтология Экосистемы OSTIS"
кавычки и жирный курсив

2022-05-24 13:28 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +	\newpage
Убрать \newpage

2022-05-24 13:32 UTC, ShunkevichDV commented on Contents/common_standart_structure.tex
> +				\end{scnitemizeiii}
Здесь почему-то большой пробел при компиляции

2022-05-29 12:18 UTC, ShunkevichDV approved these changes

2022-05-29 12:19 UTC, merged