Fix typos and contradictions in ecosystem-related concepts
ostis-ai/ostis-standard pull request #267
Opened 2022-06-01 20:26 UTC by qaip

2022-06-18 18:11 UTC, ShunkevichDV requested changes

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +\scnfileitem{Каждому специалисту, входящему в состав \textit{Экосистемы OSTIS} ставится во взаимно однозначное соответствие его \textit{персональный ostis-ассистент}, который трактуется как \textit{к
Есть такой термин, он слитно пишется

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -член ostis-сообщества*;
А что здесь смутило?

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +\scnidtf{Глобальное \textit{ostis-сообщество}, которое не может входить в состав какого-либо другого \textit{ostis-сообщества}}
Слово глобальное заменить на Максимальное, тут смысл немного в другом, в том, что не существует более общего

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{Симбиоз людей и \textit{компьютерных систем} (точнее, \textit{ostis-систем}) являющийся вариантом реализации \textit{smart-общества}}
Зачем удалять синоним, хороший синоним

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +\scnexplanation{Понятие \textit{ostis-сообщества} представляет собой не только \textit{коллектив ostis-систем}, но также определенный \textit{коллектив людей} (пользователей и разработчиков соответст
Это хорошо, что добавили, но зачем удалили нужные строки

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{субъект Экосистемы OSTIS}
не надо убирать

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{индивидуальная ostis-система, входящая в состав Экосистемы OSTIS}
не надо убирать

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnaddlevel{1}
не надо убирать это все

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +Однако внешняя среда каждого \textit{субъекта} (каждой ostis-системы и каждого человека), входящего в \textit{Экосистему OSTIS} -- это не только \textit{материальная внешняя среда*}, но и \textit{инф
ЭкосистемА обеспечивает

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -член ostis-сообщества*
Не совсем понял замену, ведь субъект это синоним агента в данном случае

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnnote{Строго говоря, все \textit{ostis-сообщества}, кроме \textit{минимальных ostis-сообществ}, являются не коллективами, состоящими из \textit{персон и ostis-систем}, а коллективами, состоящими т
не надо убирать

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{это естественный этап перехода (эволюции) творчески ориентированных коллективов людей в принципиально новое существенно более интеллектуальное и, соответственно, более позитивное качество}
не надо убирать, слово "это" можно убрать

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +        \scnidtf{\textit{ostis-сообщество}, входящее в состав заданного \textit{ostis-сообщества}}
Тут имелось в виду, что может не непосредственно входить, а быть частным по отношению к еще более частному. Надо как-то перефразировать и оставить смысл

2022-06-18 18:11 UTC, ShunkevichDV commented on Contents/chapter2/sd_ostis_ecosystem/sd_ostis_ecosystem.tex
> -\scnsubdividing{атомарная встроенная ostis-система\\
атомарная встроенная и самостоятельная - разные вещи

2022-06-20 07:29 UTC, qaip commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -член ostis-сообщества*;
По какой причине необходимо акцентировать внимание на отличие _члена ostis-сообщества*_ от _корпоративной ostis-системы*_ и _персонального ostis-ассистента*_? Как правило, на отличия указывают в том случае, если понятия в чём то пересекаются, но имеют кардинально отличительные особенности. Возможно, приведённое указание отличий и имеет здесь смысл, но лишь с подкреплённым обоснованием, как оно связано с другими понятиями и почему.

2022-06-20 08:13 UTC, qaip commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{Симбиоз людей и \textit{компьютерных систем} (точнее, \textit{ostis-систем}) являющийся вариантом реализации \textit{smart-общества}}
Во первых, такой синоним уже был дан ранее (в начале _Предметной области и онтологии деятельности в области Искусственного интеллекта_), пусть и без акцента на то, что _Экосистема OSTIS_ является вариантом реализации _smart-общества_ (а это указано несколькими строками ниже):
`Экосистема OSTIS`
`:= [симбиоз семантически совместимых и координирующих свою деятельность ostis-систем и
людей, направленный на существенное, качественное повышение уровня автоматизации всех
видов человеческой деятельности]`
Во-вторых, про такого рода симбиоз было также сказано во фрагменте _Понятие ostis-сообщества_ (25стр ранее) при описании _ostis-сообщества_, чего наряду тем, что Экосистема OSTIS является (1) ostis-сообществом и (2) вариантом реализации _smat-общества_ (уже не говоря о вышеуказанном схожем идентификаторе), вполне достаточно, чтобы самостоятельно сформировать такой синоним.

2022-06-20 08:47 UTC, qaip commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> +\scnidtf{Глобальное \textit{ostis-сообщество}, которое не может входить в состав какого-либо другого \textit{ostis-сообщества}}
О том, что _Экосистема OSTIS_ является Максимальным и не существует более общего, было сказано в предыдущем идентификаторе (максимальный уровень иерархии). Эта идея также поясняется и двумя строчками выше: `Экосистема OSTIS является максимальным ostis-сообществом, включающим в себя все существующие ostis-сообщества`. 
Указывать на одно и то же в третий раз смысла особого нету, лучше подчеркнуть именно глобальность, поскольку Экосистема включает в себя **все** существующие ostis-сообщества и является `глобальной сетью ostis-систем вместе с их пользователями` (о чём сказано 7стр ранее), т.е. оно является **глобальным** ostis-сообществом. Это раскрывает и опиcывает понятие с немного другой стороны, что дополняет уже данное определение (c акцентом на максимальности).

2022-06-20 11:15 UTC, qaip commented on Contents/chapter0/intro_ostis/intro_ostis_segment5.tex
> -\scnidtf{это естественный этап перехода (эволюции) творчески ориентированных коллективов людей в принципиально новое существенно более интеллектуальное и, соответственно, более позитивное качество}
Любое ostis-сообщество является агентом Экосистемы OSTIS, поскольку Экосистема включает в себя все существующие ostis-сообщества.
Идентификатор был перенесен в примечание и небольшим дополнением. Всё-таки естественный этап эволюции представляет собой не само ostis-сообщество (оно как раз-таки представляет реализацию этого этапа эволюции), а сама идея ostis-сообщества в рамках Экосистемы OSTIS.
По какой причине это некорректно?

2022-08-08 10:20 UTC, AlexandrZagorskiy approved these changes

2022-08-10 09:46 UTC, ShunkevichDV approved these changes

2022-08-10 09:46 UTC, merged