Add SD of biblio components
ostis-ai/ostis-standard pull request #280
Opened 2022-06-20 17:00 UTC by KsenBantsevich

2022-06-21 12:55 UTC, MksmOrlov commented on Contents/chapter2/sd_ostis_sys_models/sd_ostis_sys_models.tex
> +\label{sd_installers}
components_installer

2022-06-27 14:32 UTC, MksmOrlov requested changes
![image](https://user-images.githubusercontent.com/36566977/175965809-92802fe3-5495-4f73-8fbc-60bc9829d272.png)
либо передвинуть это разбиение на уровень влево, чтобы это было для многократно используемых компонентов, либо убрать "многократно используемый"

2022-06-30 13:59 UTC, MksmOrlov approved these changes

2022-07-12 09:08 UTC, ShunkevichDV approved these changes

2022-09-23 18:25 UTC, ShunkevichDV requested changes

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{Целостная часть ostis-системы, которая содержит все те (и только те) sc-элементы, которые необходимы для её функционирования в ostis-системе.}
Лучше явно пояснить разницу между просто компонентом и МИК, потому что разница в 1 слово не сразу понятна

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +	\scnsubdividing{многократно используемый компонент ostis-систем, хранящийся в виде файлов исходных текстов;многократно используемый компонент ostis-систем, хранящийся в виде бинарных файлов}
Может быть слово "бинарных" чем-то заменить типа скомпилированных, может быть теоретически небинарная архитектура

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnnote{Данное отношение позволяет информировать о наиболее часто скачиваемых компонентах.}
```suggestion
\scnnote{Данное отношение позволяет оценивать частоту скачивания компонентов, то есть их использования в дочерних ostis-системах.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnnote{Данное отношение позволяет хранить сведения о системах и компонентах, которые установлены в них, тем самым предоставляя возможность анализировать навыки системы.}
```suggestion
\scnnote{Данное отношение позволяет хранить сведения о системах и компонентах, которые установлены в них, тем самым предоставляя возможность анализировать функциональные возможности системы.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{Квазибинарное отношение, связывающее некоторую ostis-систему и компоненты, которые доступны к установке в конкретной ostis-системе.}
```suggestion
\scnexplanation{Квазибинарное отношение, связывающее некоторую ostis-систему и компоненты, которые доступны для установки в данной ostis-системе.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnnote{Данное отношение позволяет давать рекомендации по развитию ostis-системы, в которую можно установить многократно используемые компоненты.}
1. Не совсем понятно, как оно дает рекомендации по развитию
2. Не понятно, как формируются связки этого отношения, мы не сказали нигде про сам механизм скачивания спецификаций компонентов и механизм установки

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{Место, предназначенное для хранения многократно используемого компонента ostis-систем.}
Плохое пояснение, здесь и дальше, под него подходит что угодно, нужно развить немного и пояснить, что это такое более конкретно, привести примеры

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnnote{На данном этапе в рамках \textit{Технологии OSTIS} (в силу открытости технологии, а также хранения компонентов в виде файлов исходных текстов) для хранения компонентов используются хранилища
```suggestion
\scnnote{На данном этапе в рамках \textit{Технологии OSTIS} (в силу открытости технологии, а также хранения компонентов в виде файлов исходных текстов) для хранения компонентов чаще всего используются хранилища на основе системы контроля версий Git.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnsubset{спецификация}
нет такого понятия по-моему, надо проверить
есть семантическая окрестность

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +	\scnnote{Данный вид интерфейса позволят подключиться к библиотеке многократно используемых компонентов баз знаний, получить доступ к хранящимся там компонентам и использовать функционал библиотеки.}
```suggestion
	\scnnote{Данный вид интерфейса позволяет менеджеру многократно используемых компонентов ostis-систем, входящему в состав какой-либо дочерней ostis-системы, подключиться к библиотеке многократно используемых компонентов ostis-систем и использовать ее функциональные возможности, то есть, например, получить доступ к спецификации компонентов и установить выбранные компоненты в дочернюю ostis-систему, получить сведения до доступных версиях компонента, его зависимостях и т.д.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{ostis-система, компоненты которой входят в состав библиотеки многократно используемых компонентов.}
Не обязательно, обязательным является только наличие библиотеки

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_know_base_component.tex
> +\scnnote{Базовый фрагмент предметной области и онтологии включает в себя теоретико-множественную, логическую онтологии, а также терминологические фрагменты.}
```suggestion
\scnnote{Базовый фрагмент предметной области и онтологии включает в себя теоретико-множественную и логическую онтологию, а также фрагменты терминологической онтологии, описывающие основные идентификаторы объектов исследования предметной области.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_know_base_component.tex
> +\scnsuperset{базы знаний прикладных систем}
```suggestion
\scnsuperset{база знаний прикладной ostis-системы}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_know_base_component.tex
> +\scnnote{Целые базы знаний могут быть многократно используемыми компонентами в случае разработки интеллектуальных систем, назначение которых совпадает.}
```suggestion
\scnnote{Целые базы знаний могут быть многократно используемыми компонентами в случае разработки интеллектуальных систем, имеющих схожие функциональные требования.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_know_base_component.tex
> +\scnexplanation{\textit{Ядро базы знаний} представляет собой компонент, входящий в состав каждой базы знаний, разрабатываемой по \textit{Технологии OSTIS}, и скачивающийся в первую очередь.}
```suggestion
\scnexplanation{\textit{Ядро базы знаний} представляет собой компонент, входящий в состав каждой базы знаний, разрабатываемой по \textit{Технологии OSTIS}, и устанавливаемый в первую очередь.}
```

2022-09-23 18:25 UTC, ShunkevichDV commented on Contents/part_methods_tools/sd_know_base_component.tex
> +\scnnote{Список многократно используемых компонентов не является окончательным. В случае, когда разработчик базы знаний интеллектуальной системы считает, что разработанный им компонент сможет стать н
```suggestion
\scnnote{Список приведенных классов многократно используемых компонентов не является окончательным. В случае, когда разработчик базы знаний интеллектуальной системы считает, что разработанный им компонент сможет стать неотъемлемой частью библиотеки, то компонент будет добавлен в библиотеку, как многократно используемый, в случае, если компонент прошел верификацию и соответствует требованиям разработчиков библиотеки.}
```

2022-09-24 21:02 UTC, MksmOrlov commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnsubset{спецификация}
нашёл `sc-спецификация := [семантическая окрестность]` а ещё `вид знаний -> спецификация`, `спецификация := [описание заданной сущности]`. Есть целая иерархия спецификаций

2022-09-24 21:13 UTC, MksmOrlov commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{Бинарное отношение, связывающее два компонента, которые не могут одновременно присутствовать в одной ostis-системе.}
Могут ли в принципе быть несовместимые компоненты? Если взять разные геометрии, то ostis-системе нужно знать, когда какую стоит применять, при этом они все могут одновременно присутствовать в одной ostis-системе. Другой вопрос, что они не могут одновременно использоваться при решении одной задачи, но это уже другой класс компонентов

2022-09-24 21:16 UTC, MksmOrlov commented on Contents/part_methods_tools/sd_biblio_component.tex
> +\scnexplanation{Бинарное отношение, связывающее два компонента, которые не могут одновременно присутствовать в одной ostis-системе.}
то же самое с компонентами интерфейса, здесь ещё более наглядно. ostis-системам нужно уметь определять формальные теории, в которых решаются задачи и действовать в рамках таких, у которых противоречий нет

2022-09-25 13:52 UTC, ShunkevichDV requested changes

2022-09-25 14:04 UTC, ShunkevichDV approved these changes

2022-09-25 14:23 UTC, merged