Fix sd_actions inconsistency in basic concepts
ostis-ai/ostis-standard pull request #312
Opened 2022-10-02 23:55 UTC by KovalM

1. Уточнены понятия воздействия и действия
2. Согласованы понятия субъекта и объекта
3. Решена проблема несогласованности сегмента 4 со всем разделом
4. Незначительные исправления после вычитки

2022-10-05 15:21 UTC, ShunkevichDV requested changes

2022-10-05 15:21 UTC, ShunkevichDV commented on Contents/part_kb/sd_actions/sd_actions_intro_part.tex
> +	\scnidtf{структура (sc-конструкция), содержащая в достаточную информацию для выполнения соответствующего (специфицируемого) действия}
```suggestion
	\scnidtf{структура (sc-конструкция), содержащая достаточную информацию для выполнения соответствующего (специфицируемого) действия}
```

2022-10-05 15:21 UTC, ShunkevichDV commented on Contents/part_kb/sd_actions/sd_actions_intro_part.tex
> +\scnreltovector{конкатенация сегментов}{Уточнение понятия воздействия и понятия действия. Типология воздействий и действий;Уточнение понятия задачи. Типология задач;Уточнение семейства параметров и о
Здесь это некорректно теперь, поточу что сегменты есть у раздела, а не у ПрО

2022-10-05 15:21 UTC, ShunkevichDV commented on Contents/part_kb/sd_actions/sd_actions_segment6_7.tex
>   		\scnidtf{кибернетическая система, которая в рамках заданного действия или деятельности выполняет ту или иную роль, воздействует на некий объект действия, используя тот или иной инструмент*}
```suggestion
 		\scnidtf{кибернетическая система, которая в рамках заданного действия или деятельности выполняет ту или иную роль, воздействует на некий объект действия, используя тот или иной инструмент\scnrolesign}
```

2022-10-23 08:16 UTC, KovalM commented on Contents/part_kb/sd_actions/sd_actions_intro_part.tex
> +\scniselement{предметная область}
Было ниже, вернул в начало

2023-06-21 07:25 UTC, closed without merging