feat(part_ps): agents and ps
ostis-ai/ostis-standard pull request #339
Opened 2023-08-19 17:20 UTC by MakarenkoAI

2023-08-20 10:07 UTC, MakarenkoAI commented on Contents/part_ps/sd_agents.tex
> +                \scnitem{В случае приостановки \textit{scp-процесса} (добавления его во множество \textit{отложенных действий}) в соответствии с общими правилами синхронизации все его дочерние процес
fixed "бытьприо становлены"

2023-08-23 08:45 UTC, NikitaZotov requested changes

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ps/sd_agents.tex
> +        ~\\Особой группой полностью заблокированных \textit{sc-элементов} (на время выполнения действия \textit{\mbox{sc-агентом}}) являются вспомогательные \textit{sc-элементы} (леса), создаваемые т
```suggestion
        ~\\Особой группой полностью заблокированных \textit{sc-элементов} (на время выполнения действия \textit{\mbox{sc-агентом}}) являются вспомогательные \textit{sc-элементы} (леса), создаваемые только на время выполнения этого действия. Эти sc-элементы в конце выполнения действия должны не деблокироваться, а удаляться.}
```

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ps/sd_agents.tex
> +            ~\\\scnsuperset{действие интерпретации scp-программы}
```suggestion
            \scnsuperset{действие интерпретации scp-программы}
```

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ps/sd_ann.tex
>  %\scnrelfromset{частная предметная область}{
А чего это закомментировали?

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ui.tex
> +% \scsubsection[
Какие здесь проблемы?

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ui/sd_user_interfaces.tex
> +				~\\\scniselement{неатомарный компонент пользовательского интерфейса}
```suggestion
				\scniselement{неатомарный компонент пользовательского интерфейса}
```

2023-08-23 08:45 UTC, NikitaZotov commented on Contents/part_ui/sd_user_interfaces.tex
> +				~\\\scniselement{неатомарный компонент пользовательского интерфейса}
Везде перед макросами их лучше убрать

2023-08-24 10:03 UTC, NikitaZotov requested changes

2023-08-31 09:39 UTC, NikitaZotov commented on Contents/part_ecosystem/ims_ostis.tex
> +            \scnitem{Sc-модель Метасистемы IMS.ostis}
```suggestion
            \scnitem{SC-модель Метасистемы IMS.ostis}
```

2023-08-31 11:23 UTC, NikitaZotov approved these changes

2023-09-05 08:51 UTC, merged