Feat/soft platform
ostis-ai/ostis-standard pull request #347
Opened 2023-11-07 16:30 UTC by NikitaZotov

2023-11-30 08:52 UTC, ShunkevichDV requested changes

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +	\scnnote{Логически текущий \textit{Программный интерфейс Реализации sc-памяти} разделяется на два программных интерфейса: \textbf{\textit{Программный интерфейс информационно-формирующих методов Реал
```suggestion
	\scnnote{Логически текущий \textit{Программный интерфейс Реализации sc-памяти} разделяется на два программных интерфейса: \textbf{\textit{Программный интерфейс информационно-формирующих методов Реализации sc-памяти}} и \textbf{\textit{Программный интерфейс информационно-поисковых методов Реализации sc-памяти}}. В первую очередь, такое разделение связано с тем, что реализация методов информационного поиска в текущей \textit{Реализации sc-памяти} достаточна сложна и требует намного большего уточнения при описании этой реализации. Также это разделение \textit{программного интерфейса} позволяет выделять и структурировать спецификацию методов \textit{Программного интерфейса Реализации sc-памяти} таким образом, чтобы она оставалась однообразной, компактной и простой для внешнего пользователя. Как такового физического разделения в \textit{Программном интерфейсе Реализации sc-памяти} не существует, все методы \textit{Программного интерфейса Реализации sc-памяти} могут быть использованы одним и тем же программным образом и являются компонентами \textbf{\textit{Библиотеки многократно используемых компонентов Программного варианта реализации ostis-платформы}}, то есть могут быть использованы при реализации других компонентов специального назначения.}
```

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +	\scnnote{Логически текущий \textit{Программный интерфейс Реализации sc-памяти} разделяется на два программных интерфейса: \textbf{\textit{Программный интерфейс информационно-формирующих методов Реал
Кроме того, не совсем удачная фраза "использованы программным образом"

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +			\scnsubset{программный объект}
Звучит очень нездорово. Это во-первых вроде как класс, а не объект, во-вторых объект это что угодно. Может быть можно как-то назвать по-другому

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +		\scnexplanation{Для \textit{Метода создания итератора поиска трехэлементных конструкций в sc-памяти}, как и для \textit{Метода создания итератора поиска пятиэлементных конструкций в sc-памяти} можн
Я бы предложил пояснить, что f это те операнды, которые известны на момент начала выполнения фукнции, а а - нет. Ну или что-то в этом духе. То есть пояснить, для чего это вводится вообще

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +		\item существующие алгоритмы либо медленны, либо нерационально используют память, что приводит \textit{изоморфный поиск} к медленной работе.
Неудачная фраза "приводит \textit{изоморфный поиск} к медленной работе"

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +			\item На уровне \textit{Программного интерфейса Реализации sc-памяти} никак не ограничивается диапозон классов sc-элементов в sc-памяти, которые могут быть установлены в качестве аргументов, напри
диапАзон

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +		\scntext{пояснение}{Реализация подсистемы взаимодействия c sc-памятью на основе языка JSON позволяет ostis-системам взаимодействовать с системами из внешней среды на основе общепринятого транспортн
Лишний отступ, проверь везде пожалуйста

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +		\scnitem{Тексты, описываемые на языке внешнего представления знаний \textit{\textbf{SC-JSON-код}} представляют собой линейную структуру, представляемую в виде линейного строкового текста и состоящу
Нужны файлы

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +			\scnfileitem{sc-json-списки, состоящие не из sc-json-пар, начинаются знаком открывающейся квадратной скобки \scnqq{} и заканчиваются знаком закрывающейся квадратной скобки \scnqq{}. sc-json-объект
Пропущены скобки сами

2023-11-30 08:52 UTC, ShunkevichDV commented on Contents/part_platform/sd_program_interp.tex
> +		\scnheader{команда н
Тут тоже либо закомментить, либо ссылку на раздел вставить

2023-12-25 19:25 UTC, NikitaZotov commented on Contents/part_platform/sd_program_interp.tex
> +	\begin{scnitemize}
Видимо не залито. Залью отдельным ПР и пройдусь автозаменой по всему тексту

2023-12-25 19:26 UTC, NikitaZotov commented on Contents/part_platform/sd_program_interp.tex
> +	\begin{scnitemize}
Пока в Стандарте везде используются квадратики, мячики были в Монографии

2024-01-03 17:42 UTC, ShunkevichDV approved these changes

2024-01-04 09:01 UTC, merged