formalisation of chapter 5.1 Yurhilevich Eugene 221702
ostis-ai/ostis-standard pull request #355
Opened 2023-12-21 17:24 UTC by KL1cktm

2023-12-21 17:24 UTC, KL1cktm commented
Глава 5.1 формализованный результат

2023-12-24 19:56 UTC, MksmOrlov requested changes

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{назначение}{Позволяет уменьшить трудоемкость создания компьютерных систем и их стоимость (путем минимизации количества труда за счет отсутствия необходимости разрабатывать какой-либо компо
В конце предложений (ЕЯ-вставок) нужно ставить точку

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{пояснение}{Технология компонентного проектирования интеллектуальных
здесь нужно выделить сущность "технология компонентного проектирования интеллектуальных компьютерных систем" и делать явными отношения включение* к каждой частной технологии

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scniselement{термин}
Что тут имеется ввиду? Выглядит лишним или поясни, чтобы я понял, зачем оно все-таки надо

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{разработка}{Многократная повторная разработка уже имеющихся технических решений обусловлена либо тем, что известные технические решения плохо плохо интегрируются в разрабатываемую систему,
странное отношение "разработка", оно здесь точно не подходит

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scnrelfrom{рисунок}{\scnfileimage[20em]{Contents/part_methods_tools/src/images/sd_ostis_library/configuration_file.png}}
нужно экранировать символы подчеркивания как "\_"

2023-12-24 19:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{поддерживает}{Базовую технологию разработки прикладных и специализированных инструментальных (интеллектуальных) сервисов с использованием базовых инструментальных сервисов платформы,
Здесь неправильно формализовано. Нужно разделить на два предложения (два отношения) то, что в пояснении сейчас и "предоставляет доступ"...

2023-12-25 18:51 UTC, MksmOrlov requested changes

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
Аннотацию нужно обновить. В монографии она более полная
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/7c29b954-f046-4da0-9e94-edfa14878e57)

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scnheader{Компонентное проектирование интеллектуальных компьютерных систем}
Это всё должно идти после спецификации ПрО (после блока, фрагмент которого на скрине)
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/1f1bc5ff-c5ec-43c3-910e-e6a3191e4e97)

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scnheader{Компонентное проектирование интеллектуальных компьютерных систем}
должно быть с маленькой буквы это понятие

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
Будет очень большая польза,если добавишь список источников в библиографию (перекопировать из монографии)
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/54f2f5f7-affa-4f04-a2de-5b1e99c0cd92)

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{зависимость}{Проектируемые системы обладают высоким уровнем гибкости, их разработка осуществляется поэтапно, переходя от одной целостной версии системы к другой. При этом стартовая версия
не похоже на зависимость и тем более не тут должно описываться. Внизу есть понятие библиотеки уже

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
Не все формализовано, например, в введении много пропущено

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scnsubset{Технология интерфейсов}
нет таких понятий. Нужно писать полностью

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{пояснение}{Отношение, которое используется для выявления недостатков и преимуществ использования библиотек компонентов.}
это лишнее

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{поиск}{Поиск компонентов в библиотеках компонентов, соответствующих данных пакетным менеджерам сводится к поиску по идентификатору компонента.}
отношение "поиск" здесь не подходит. Здесь описывается скорее недостаток

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{ориентация}{Современные библиотеки компонентов ориентированы только на какой-то определенный язык программирования, операционную систему или платформу.}
это тоже недостаток

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scnitem{OWL}
это должно быть scnheader,а не item. Новое понятие, которое описывается. Такая конструкция некорректна
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/aae830a1-3182-417d-a086-cfb1fa25b798)

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scnitem{Modelica}
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/179747a8-b343-4fea-ae6e-e5788843266d)
здесь отступ поехал

2023-12-25 18:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scnitem{Modelica}
и много где тоже

2023-12-26 08:45 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        	\begin{scnindent}
слишком много отступов. Это неправильно. Ниже слишком много закрывающихся отступов

2023-12-26 08:46 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \item сервисам управления}
здесь должны быть скобки и scnfileitem вместо item

2024-01-04 18:44 UTC, merged