Update part 2.4
ostis-ai/ostis-standard pull request #372
Opened 2024-01-06 13:27 UTC by MakarenkoAI

1. Предметная область и онтология материальных сущностей 
2. Предметная область и онтология пространственных сущностей
Эти две ПрО не описаны в монографии. Скорее всего формализованно самостоятельно студентом + некоторые фрагменты взяты из монографии

2024-01-14 20:20 UTC, MksmOrlov requested changes

2024-01-14 20:20 UTC, MksmOrlov commented on Contents/part_kb/src/sd_material_entities.tex
> +	\scntext{вступление}{В данной статье рассмотрена структура онтологии предметной области материальных сущностей, взаимосвязь предметной области с другими предметными областями верхнего уровня.}
не вступление, а аннотация. Не статья, а ПрО

2024-01-14 20:20 UTC, MksmOrlov commented on Contents/part_kb/src/sd_material_entities.tex
> +	\scntext{пояснение}{\textbf{\textit{предметная область}} --- это результат интеграции (объединения) частичных семантических окрестностей, описывающих все исследуемые сущности заданного класса и имею
весь текст, который не относится к материальным сущностям нужно убрать. Это есть в ПрО предметных областей. Здесь только маты оставить

2024-01-14 20:20 UTC, MksmOrlov commented on Contents/part_kb/src/sd_material_entities.tex
Это бесполезный и неправильный кусок текста, который дублирует другие ПрО (ПрО и временных сущностей) и почти никак не описывает материальные сущности. Предлагаю убрать его

2024-01-14 20:20 UTC, MksmOrlov commented on Contents/part_kb/src/sd_spatial_entities.tex
Это бесполезный и неправильный кусок текста, который дублирует другие ПрО и почти никак не описывает пространственные сущности. Предлагаю убрать его

2024-01-17 17:47 UTC, MksmOrlov requested changes
добавь в описание ПР в котором материальные сущности добавляешь

2024-01-17 17:47 UTC, MksmOrlov commented on Contents/part_kb/src/images/car.png
Не используется. Удали

2024-01-17 17:47 UTC, MksmOrlov commented on Contents/part_kb/src/images/orm.png
Не используется. Удали

2024-01-18 13:20 UTC, MksmOrlov approved these changes

2024-01-28 15:57 UTC, SHtress approved these changes

2024-01-28 17:49 UTC, merged