Mono library
ostis-ai/ostis-standard pull request #373
Opened 2024-01-09 20:08 UTC by MksmOrlov

перенос главы 5.1 из монографии в стандарт.
После мержа планируется выделить сегменты. Это не сделано в этом ПРе для удобства проверки, иначе пришлось бы разбивать на отдельные файлы, где изменения невозможно отследить.
План работ:
- добавление сегментов
- добавление библиографических источников
- добавление примеров компонентов

2024-01-15 15:55 UTC, MakarenkoAI requested changes

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                	\scnhaselement{Предметная область множеств}
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/5077af28-3d6f-4ca3-b71e-13f9513ecccd)
чисел/множеств

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{В случае \textit{неатомарного многократно используемого компонента} это означает, что \uline{все} более простые компоненты, входящие в его состав также обязан
```suggestion
                    \scntext{примечание}{В случае \textit{неатомарного многократно используемого компонента} ЭТО означает, что \uline{все} более простые компоненты, входящие в его состав также обязаны быть платформенно-независимыми многократно используемыми компонентами ostis-систем.}
```
что это?

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
>          \scnrelfrom{описание примера}{\scnfileimage[20em]{Contents/part_methods_tools/src/images/sd_ostis_library/component_specification_example.png}}
картинку можно побольше сделать

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                \scntext{примечание}{Чтобы многократно используемый компонент мог быть принят в библиотеку, нужно специфицировать его используя каждое отношение из множества \textit{необходимое для у
```suggestion
                \scntext{примечание}{Чтобы многократно используемый компонент мог быть принят в библиотеку, нужно специфицировать его, используя каждое отношение из множества \textit{необходимое для установки отношение, специфицирующее многократно используемый компонент ostis-систем}. Здесь описана спецификация, общая для любых типов компонентов, однако в зависимости от типа компонента, спецификация может расширяться.}
```

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
>          \scnheader{метод установки*}
Пользователь может установить компонент вручную, а \scnkeyword{менеджер компонентов} **---** автоматически.
тройное --- на строке 675

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{пояснение}{В некоторых случаях может оказаться, что для использования одного многократно используемого компонента OSTIS целесообразно или даже необходимо дополнительно использовать н
```suggestion
        \scntext{пояснение}{В некоторых случаях может оказаться, что для использования одного многократно используемого компонента OSTIS целесообразно или даже необходимо дополнительно использовать несколько других \textit{многократно используемых компонентов OSTIS}. Например, может оказаться целесообразным вместе с КАКИМ-ЛИБО sc-агентом информационного поиска использовать соответствующую команду интерфейса, которая представлена отдельным компонентом и позволит пользователю задавать вопрос для указанного sc-агента через интерфейс системы. В таких случаях для связи компонентов используется отношение \textit{сопутствующие компоненты*}. Наличие таких связей позволяет устранить возможные проблемы неполноты знаний и навыков в дочерней системе, из-за которых какие-либо из компонентов могут не выполнять свои функции. Связки отношения \textit{сопутствующий компонент*} связывают многократно используемые компоненты ostis-систем, которые целесообразно использовать в дочерней системе вместе. Каждая такая связка может дополнительно быть снабжена sc-комментарием или sc-пояснением, отражающим суть указываемой зависимости.}
```
 каким-либо

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scnheader{авторы*}
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/928ae7cb-c939-4452-8464-a11d255c82e7)
не нашла этого
И отделяй \scnheader пустой строкой, пожалуйста, читать неудобно

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
>          \scnheader{менеджер многократно используемых компонентов ostis-систем}
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/d34bd72b-b80f-46c4-9b7f-56c9fae86414)

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                \scntext{примечание}{база знаний менеджера компонентов содержит все те знания, которые необходимы для установки многократно используемого компонента в \scnkeyword{дочернюю ostis-систе
```suggestion
                \scntext{примечание}{база знаний менеджера компонентов содержит все те знания, которые необходимы для установки многократно используемого компонента в \scnkeyword{дочернюю ostis-систему}. К таким знаниям относятся знания о спецификации многократно используемых компонентов, методы установки компонентов, знание о  библиотеках ostis-систем, с которыми происходит взаимодействие, \textit{Классификация компонентов} и другие.}
```

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        	\scntext{примечание}{Используя минимальные функциональные возможности менеджер компонентов может установить компоненты, которые будут расширять его же функционал.}
```suggestion
        	\scntext{примечание}{Используя минимальные функциональные возможности, менеджер компонентов может установить компоненты, которые будут расширять его же функционал.}
```

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                \scntext{примечание}{решатель задач менеджера компонентов взаимодействует с библиотекой ostis-систем и позволяет установить и интегрировать многократно используемые компоненты в \scnk
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/6d3d6982-6dee-41ba-935a-258825c3249c)
примечания нет

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        		\scnfileitem{\textbf{Формирование} многократно используемого компонента ostis-систем по шаблону с заданными параметрами. При установке шаблона многократно используемого компонента ostis-сис
```suggestion
        		\scnfileitem{\textbf{Формирование} многократно используемого компонента ostis-систем по шаблону с заданными параметрами. При установке шаблона многократно используемого компонента ostis-систем менеджер компонентов позволяет сформировать по нему конкретный компонент. Для этого пользователю предлагается определить значения всех sc-переменных в шаблоне для формирования конкретного компонента из некоторой предметной области. Например, для формирования многократно используемого компонента баз знаний, представляющего собой семантическую окрестность некоторого отношения (см. рисунок **_\textit{\nameref{fig:relation_template}})_**, нужно определить значения всех переменных, кроме переменной, являющейся ключевым sc-элементом данной структуры.}
```
какой рисунок?

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{примечание}{Для того, чтобы создать новую ostis-систему "с нуля"{}, используя \textit{ostis-платформу}, необходимо установить некоторый \textit{Программный вариант реализации ostis-п
```suggestion
        \scntext{примечание}{Для того, чтобы создать новую ostis-систему \scnqq{с нуля}, используя \textit{ostis-платформу}, необходимо установить некоторый \textit{Программный вариант реализации ostis-платформы} с помощью сторонних средств. Такими средствами могут быть (1) хранилища исходного кода платформы, например, облачные хранилища, такие как GitHub репозиторий, с соответствующим набором инструкций по установке платформы или (2) средства установки заранее скомпилированной программной реализации платформы, например, средство установки программного обеспечения apt. Далее установка многократно используемых компонентов в ostis-систему (независимо от типа компонентов) осуществляется с помощью менеджера компонентов. При установке платформенно-зависимых компонентов менеджер компонентов должен управлять соответствующими средствами сборки таких компонентов (CMake, Ninja, npm, grunt и другие).}
```

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        	\scntext{примечание}{Для реализации компонентного подхода предлогается \textit{библиотека многократно используемых совместимых компонентов интеллектуальных компьютерных систем на основе Техн
```suggestion
        	\scntext{примечание}{Для реализации компонентного подхода предлагается \textit{библиотека многократно используемых совместимых компонентов интеллектуальных компьютерных систем на основе Технологии OSTIS}, введена классификация и спецификация многократно используемых компонентов ostis-систем, предложена модель менеджера компонентов, позволяющего взаимодействовать \textit{ostis-системам} с \textit{библиотеками многократно используемых компонентов} и управлять компонентами в системе, рассмотрена архитектура экосистемы \textit{интеллектуальных компьютерных систем} с точки зрения использования библиотеки многократно используемых компонентов.}
```

2024-01-15 15:55 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{примечание}{\scnkeyword{Microsoft Power Apps} --- это набор приложений, служб и соединителей, а также платформа данных, которая предоставляет среду разработки для эффективного создания пол
```suggestion
		\scntext{примечание}{\scnkeyword{Microsoft Power Apps} --- это набор приложений, служб и соединителей, а также платформа данных, которая предоставляет среду разработки для эффективного создания пользовательских приложений для бизнеса. Платформа \textit{Microsoft Power Apps} имеет средства для создания библиотеки многократно используемых компонентов графического интерфейса, а также предварительно созданные модели распознавания текста (чтение визитных карточек или чеков) и СРЕДСТВО ОБНАРУЖЕНИЯ объектов, которые можно подключить к разрабатываемому приложению. Библиотека компонентов \textit{Microsoft Power Apps} представляет собой множество создаваемых пользователем компонентов, которые можно использовать в любых приложениях. Преимущество библиотеки в том, что компоненты могут настраивать свойства по умолчанию, которые можно гибко редактировать в любых приложениях, использующих компоненты. Недостаток в том, что отсутствует семантическая совместимость компонентов, спецификация компонентов, не решена проблема существования семантически эквивалентных компонентов, НЕТ иерархии компонентов и средств поиска этих компонентов. Компоненты платформы \textit{Microsoft Power Apps} являются многократно используемыми только для однотипных приложений, которые создаются одним и тем же разработчиком.}
```
обнаружениЯ объектов
нетУ -> нет

2024-01-15 19:39 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scntext{преимущество}{Позволяет проектировать интеллектуальные системы комбинируя уже существующие компоненты, выбирая нужные из соответствующих библиотек. Использование готовых компонентов предпо
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/5657eb67-c7ed-4eac-b72c-4690b5144d36)

2024-01-15 19:40 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                \scntext{примечание}{решатель задач менеджера компонентов взаимодействует с библиотекой ostis-систем и позволяет установить и интегрировать многократно используемые компоненты в \scnk
эти слова в формализации уже есть. В монографии это вода и связующие слова

2024-01-15 19:46 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +	\scntext{примечание}{Термин "библиотека подпрограмм", одними из первых упомянули Уилкс М., Уиллер Д. и Гилл С. в качестве одной из форм организации вычислений на компьютере. Исходя из изложенного в
qqi is a single quotes as I remember

2024-01-15 19:47 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +		\scnfileitem{пакетные менеджеры не учитывают семантику компонентов, а только лишь устанавливают компоненты по идентификатору. Библиотеки таких компонентов являются только лишь хранилищем компоненто
выделять необязательно. Маленькая буква обязательна

2024-01-15 19:52 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{примечание}{Проблема интеграции многократно используемых компонентов ostis-систем решается путем взаимодействия компонентов через общую базу знаний. Интеграция многократно используем
нет 
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/951725ad-e17a-430b-8b8b-3aa8da8357dd)

2024-01-15 20:01 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                	\scnhaselement{Предметная область множеств}
что не так?

2024-01-15 21:25 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                	\scnhaselement{Предметная область множеств}
Предметную область чисел потерял
Но если так задумано, то вопросов нет

2024-01-17 17:50 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_biblio_component.tex
>              \scnfileitem{Хранение многократно используемых компонентов ostis-систем и их спецификаций.}
хотя бы запятые поставить

2024-01-22 20:15 UTC, MakarenkoAI approved these changes

2024-01-27 20:46 UTC, NikitaZotov requested changes

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +            \scntext{примечание}{материнская ostis-система отвечает за какой-то класс компонентов и является САПРом для этого класса, например, содержит методики разработки таких компонентов, их клас
Сокращения пишем через точки или заглавными?

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{Принадлежность МИК ostis-систем классу атомарных компонентов зависит от того, как специфицирован этот компонент, и от существующих на данный момент компоненто
тоже

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{С точки зрения \textit{Технологии OSTIS} любая платформа интерпретации sc-моделей компьютерных систем является платформенно-зависимым многократно используемым
```suggestion
                    \scntext{примечание}{С точки зрения \textit{Технологии OSTIS} любая ostis-платформа является платформенно-зависимым многократно используемым компонентом.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{пояснение}{Под платформенно-независимым многократно используемым компонентом ostis-систем понимается компонент, который целиком и полностью представлен на \textit{SC-коде
целиком != полностью?

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{В общем случае атомарный компонент может перейти в разряд неатомарных в случае, если будет принято решение выделить какую-то из его частей в качестве отдельно
```suggestion
                    \scntext{примечание}{В общем случае атомарный компонент может перейти в разряд неатомарных в случае, если будет принято решение выделить какую-то из его частей в качестве отдельного компонента. Все вышесказанное, однако, не означает, что даже в случае его платформенной независимости, атомарный компонент всегда хранится в sc-памяти как сформированная sc-структура. Например, платформенно-независимая реализация sc-агента всегда будет представлена набором \textit{scp-программ}, но будет \textit{атомарным многократно используемым компонентом ostis-систем} в случае, если ни одна из этих программ не будет представлять интереса как самостоятельный компонент.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                \scntext{примечание}{база знаний менеджера компонентов содержит все те знания, которые необходимы для установки многократно используемого компонента в \scnkeyword{дочернюю ostis-систе
```suggestion
                \scntext{примечание}{база знаний менеджера компонентов содержит все те знания, которые необходимы для установки многократно используемого компонента в \scnkeyword{дочернюю ostis-систему}. К таким знаниям относятся знания о спецификации многократно используемых компонентов, методы установки компонентов, знание о библиотеках ostis-систем, с которыми происходит взаимодействие, \textit{классификация компонентов} и другие.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        	\scntext{примечание}{Компонентный подход является ключевым в технологии проектирования интеллектуальных компьютерных систем. Вместе с этим, технология компонентного проектирования тесно связ
```suggestion
        	\scntext{примечание}{Компонентный подход является ключевым в технологии проектирования интеллектуальных компьютерных систем. Вместе с этим, технология компонентного проектирования тесно связана с остальными составляющими \textit{технологии проектирования интеллектуальных компьютерных систем} и обеспечивает их совместимость, производя мощнейший синергетический эффект при использовании всего комплекса частных технологий проектирования интеллектуальных систем. Важнейшим принципом в реализации компонентного подхода является семантическая совместимость многократно используемых компонентов, что позволяет минимизировать участие программистов в создании новых компьютерных систем и в совершенствовании существующих компьютерных систем.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{примечание}{Сам многократно используемый компонент в рамках спецификации является \textit{ключевым sc-элементом}, а также может иметь множество своих ключевых sc-элементов.}
```suggestion
        \scntext{примечание}{Сам многократно используемый компонент в рамках спецификации является \textit{ключевым sc-элементом\scnrolesign}, а также может иметь множество своих ключевых sc-элементов.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{Спецификация неатомарного многократно используемого компонента должна содержать информацию о том, из каких компонентов он состоит, используя отношение декомпо
```suggestion
                    \scntext{примечание}{Спецификация неатомарного многократно используемого компонента должна содержать информацию о том, из каких компонентов он состоит, используя отношение декомпозиция*. При этом sc-структура, обозначающая неатомарный компонент, не обязана содержать все sc-элементы компонентов, на которые она декомпозируется, достаточно, чтобы неатомарному компоненту принадлежали знаки всех тех компонентов, из которых он состоит. Должно быть полное перечисление составных компонентов).}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{Спецификация неатомарного многократно используемого компонента должна содержать информацию о том, из каких компонентов он состоит, используя отношение декомпо
```suggestion
                    \scntext{примечание}{Спецификация неатомарного многократно используемого компонента должна содержать информацию о том, из каких компонентов он состоит, используя отношение декомпозиция*. При этом sc-структура, обозначающая неатомарный компонент не обязана содержать все sc-элементы компонентов, на которые она декомпозируется, достаточно, чтобы неатомарному компоненту принадлежали знаки всех тех компонентов, из которых он состоит. Должно быть полное перечисление составных компонентов.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +        \scntext{примечание}{Основной признак классификации многократно используемых компонентов является признак предметной области, к которой относится компонент. Здесь структура может быть довольн
```suggestion
        \scntext{примечание}{Основной признак классификации многократно используемых компонентов является признак предметной области, к которой относится компонент. Здесь структура может быть довольно богатой в соответствии с иерархией областей человеческой деятельности. Существует также множество предметно-независимых многократно используемых компонентов, которые могут использоваться в любой предметной области.}
```

2024-01-27 20:46 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +
Мне казалось раньше, что у тебя было описано Ядро. Почему его сейчас нет?

2024-01-28 14:41 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +            \scntext{примечание}{материнская ostis-система отвечает за какой-то класс компонентов и является САПРом для этого класса, например, содержит методики разработки таких компонентов, их клас
не знаю, где как. У нас кажется не стандартизировано это

2024-01-28 14:41 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{примечание}{Принадлежность МИК ostis-систем классу атомарных компонентов зависит от того, как специфицирован этот компонент, и от существующих на данный момент компоненто
не знаю, где как. У нас кажется не стандартизировано это

2024-01-28 14:42 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +                    \scntext{пояснение}{Под платформенно-независимым многократно используемым компонентом ostis-систем понимается компонент, который целиком и полностью представлен на \textit{SC-коде
=

2024-01-28 14:46 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +
не было

2024-01-28 18:30 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +            \scntext{примечание}{материнская ostis-система отвечает за какой-то класс компонентов и является САПРом для этого класса, например, содержит методики разработки таких компонентов, их клас
я писал через точки, давай через точки. Это правильнее

2024-01-28 18:31 UTC, NikitaZotov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +
Разве?

2024-01-28 18:33 UTC, NikitaZotov reviewed
.

2024-01-28 19:50 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +            \scntext{примечание}{материнская ostis-система отвечает за какой-то класс компонентов и является САПРом для этого класса, например, содержит методики разработки таких компонентов, их клас
почему это правильнее? потому что ты писал?

2024-01-28 19:50 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +
покажи, где есть

2024-01-28 19:53 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_biblio_component.tex
> +            \scntext{примечание}{материнская ostis-система отвечает за какой-то класс компонентов и является САПРом для этого класса, например, содержит методики разработки таких компонентов, их клас
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/49947b80-f701-4fd7-a6f0-ae8a5d5f7d47)
в Метасистеме писали так

2024-01-28 19:54 UTC, NikitaZotov approved these changes

2024-01-28 20:36 UTC, merged