Mono interfaces 4.1
ostis-ai/ostis-standard pull request #377
Opened 2024-01-21 16:51 UTC by MksmOrlov

4.1 Общие принципы организации интерфейсов ostis-систем (в стандарте 603 стр, ПрОиО интерфейсов ostis-систем)

Библиографию не добавлял

2024-01-24 08:39 UTC, MikhailSadovsky commented on Contents/part_ui.tex
> +\scntext{аннотация}{В предметной области рассмотрены принципы организации \textit{интерфейсов интеллектуальных компьютерных систем нового поколения}. Ключевыми свойствами \textit{интерфейсов интеллек
```suggestion
\scntext{аннотация}{В предметной области рассмотрены принципы организации \textit{интерфейсов интеллектуальных компьютерных систем нового поколения}. Ключевыми свойствами \textit{интерфейсов интеллектуальных компьютерных систем нового поколения} являются адаптивность и мультимодальность, что обеспечивает переход от парадигмы грамотного пользователя к парадигме равноправного сотрудничества пользователя с интеллектуальной системой, а также позволяет повысить эффективность человеко-машинного взаимодействия. В предметной области рассматривается подход к обеспечению указанных свойств на основе онтологической модели интерфейса и онтологической модели процесса проектирования интерфейсов.}
```

2024-01-24 08:45 UTC, MikhailSadovsky commented on Contents/part_ui.tex
> +	\item{Структура \textit{интеллектуальных интерфейсов} включает базу знаний, модуль управления взаимодействием пользователя с системой.}
здесь и далее лучше использовать полностью "адаптивный интеллектуальный мультимодальный пользовательский интерфейс", тк у интеллектуального есть отдельное определение, а здесь именно предлагаемый нами, его 1м словом не пишем так

2024-01-25 10:08 UTC, MikhailSadovsky commented on Contents/part_ui.tex
> +	\item{Структура \textit{интеллектуальных интерфейсов} включает базу знаний, модуль управления взаимодействием пользователя с системой.}
еще актуально, ниже по тексту в этом же файле тоже вместо интеллектуальный лучше писать полностью

2024-01-25 18:39 UTC, MksmOrlov commented on Contents/part_ui.tex
> +	\item{Структура \textit{интеллектуальных интерфейсов} включает базу знаний, модуль управления взаимодействием пользователя с системой.}
в этом файле обновил

2024-01-26 11:01 UTC, MakarenkoAI requested changes

2024-01-26 11:01 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_user_interface_agents_actions.tex
> +		\end{scnitemize}
```suggestion
		\begin{scnitemize}
			\item{Проверяется тип входного компонента пользовательского интерфейса (атомарный или неатомарный).}
			\item{Если \textit{компонент пользовательского интерфейса} является атомарным, то отобразить его графическое представление на основании указанных для него свойств. В случае, если данный компонент не входит в \textit{декомпозицию} любого другого \textit{компонента пользовательского интерфейса} --- завершить выполнение. Иначе определить компонент, в \textit{декомпозицию} которого входит рассматриваемый компонент пользовательского интерфейса, применить его свойства для текущего атомарного компонента и начать обработку найденного неатомарного компонента, перейдя к первому пункту.}
			\item{Если \textit{компонент пользовательского интерфейса} является неатомарным, то проверить, были ли отображены компоненты, на которые он был декомпозирован. Если да, то завершить выполнение, иначе определить еще не отображенный компонент из декомпозиции обрабатываемого неатомарного компонента и начать обработку найденного компонента, перейдя к первому пункту.}
		\end{scnitemize}
```

2024-01-26 12:36 UTC, MikhailSadovsky approved these changes

2024-01-26 19:42 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interfaces.tex
> +	\end{scnindent}
все в порядке. Это пояснение к сущности решатель задач пользовательского интерфейса ostis-систем

2024-01-27 15:44 UTC, MakarenkoAI requested changes

2024-01-27 16:25 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interfaces.tex
> +\scnidtf{\textit{пользовательский интерфейс}, который может предположить дальнейшие действия пользователей и представить информацию на основе этого предположения}
в чем разница?

2024-01-27 16:26 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interfaces.tex
> +\scnidtf{\textit{пользовательский интерфейс}, который может предположить дальнейшие действия пользователей и представить информацию на основе этого предположения}
представить тут в смысле отобразить. А предоставить как будто более широкое понятие

2024-01-27 16:31 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interface_messages.tex
> +\scnheader{сообщение}
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/cfcb57ad-67ed-4782-844f-7d91ee695448)

2024-01-27 16:34 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interface_messages.tex
> +\scnheader{сообщение}
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/0b0937d1-4b91-4ba6-be3b-224a89729699)

2024-01-27 16:35 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interface_messages.tex
> +\scnheader{сообщение}
или считаешь нужно добавить этот текст?

2024-01-27 16:35 UTC, MksmOrlov commented on Contents/part_ui/src/sd_user_interface_agents_actions.tex
> +\scnheader{решатель задач пользовательского интерфейса ostis-систем}
Это фрагмент из ПрО действий. Тут он дублируется

2024-01-27 16:39 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_user_interfaces.tex
> +\scnidtf{\textit{пользовательский интерфейс}, который может предположить дальнейшие действия пользователей и представить информацию на основе этого предположения}
представить для меня тут звучит = вообразить

2024-01-27 16:40 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_user_interfaces.tex
> +\scnidtf{\textit{пользовательский интерфейс}, который может предположить дальнейшие действия пользователей и представить информацию на основе этого предположения}
тогда уже представить информацию в чем-то ( в sc-коде, в тексте и тп)

2024-01-27 16:40 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_user_interface_messages.tex
> +\scnheader{сообщение}
может и не нужно

2024-01-27 16:50 UTC, MakarenkoAI approved these changes

2024-01-27 18:18 UTC, merged