Update: part 2.5 from monography to standard
ostis-ai/ostis-standard pull request #378
Opened 2024-01-22 20:26 UTC by MakarenkoAI

2024-01-26 19:34 UTC, MksmOrlov requested changes
1. Добавь аннотацию из монографии к ПрО баз знаний
2. не нашёл куска введения на скрине
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/42322c81-d41c-4155-9372-c655927d0dbb)
3. не нашел картинки в структурах
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/244e5333-66c6-48a1-8028-68c054d626e1)
4. в семикрах не нашел 
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/63aefebe-444f-4c54-bee6-6c68b0db67a1)
5. в ПрО онтологий не хватает этого важного фрагмента текста. 
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/9b4038ad-0bbd-415c-8464-6d408544787f)

2024-01-26 19:34 UTC, MksmOrlov commented on Contents/part_kb/src/sd_ontologies.tex
> +            \scnheader{DOLCER}
```suggestion
            \scnheader{DOLCE}
```

2024-01-27 18:31 UTC, MksmOrlov approved these changes

2024-02-04 22:53 UTC, NikitaZotov approved these changes

2024-02-05 09:05 UTC, merged