part 1.1 Cybernetic systems
ostis-ai/ostis-standard pull request #379
Opened 2024-01-25 07:31 UTC by PetrochukKsenija

2024-01-25 14:55 UTC, MakarenkoAI requested changes

2024-01-25 14:55 UTC, MakarenkoAI commented on Contents/part_intro/src/intro_hs/intro_hs_segment5.tex
> +        \scnitem{рефлексивность информации, хранимой в памяти кибернетической системы}
```suggestion
        \scnitem{рефлексивность информации, хранимой в памяти кибернетической системы}
        \end{scnrelfromlist}
```

2024-01-25 14:55 UTC, MakarenkoAI commented on Contents/part_intro/src/intro_hs/intro_hs_segment6.tex
> +        частности, \textit{уровень интеллекта кибернетической системы.}
```suggestion
        \textit{деятельности кибернетической системы}, которые определяют качество и, в
        частности, \textit{уровень интеллекта кибернетической системы.}}
```

2024-01-26 19:54 UTC, MksmOrlov commented
> И еще нужно отформатировать код, поправить отступы, пустые строки и т. д.

это совсем необязательно. слишком много времени на форматирование ручное уйдет. Надо исправлять только по тексту

2024-01-27 16:42 UTC, MksmOrlov requested changes
почини компиляцию и комментарии Анны, она в том числе указывала, из-за чего не билдится

![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/8cea1b16-2f68-4081-b307-eac48e68afc8)

2024-01-31 13:27 UTC, MakarenkoAI reviewed
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/69581d9e-8acc-4a6f-a36d-10ffa4a99521)
Вот эту аннотацию добавить нужно, не знаю к чему только :)

2024-02-08 20:16 UTC, MksmOrlov requested changes

2024-02-08 20:16 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +        \scnitem{трудоемкость и темпы приобретения (расширения) и совершенствования активно используемых знаний
```suggestion
        \scnitem{трудоемкость и темпы приобретения и совершенствования активно используемых знаний
```
Иначе это понятие не склеиться с тем, что ниже без скобок

2024-02-08 20:16 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +        \scnitem{способность к постоянному мониторингу и поддержке своей совместимости как с другими компьютерными
"способность к постоянному мониторингу и поддержке своей совместимости" это понятие, а весь остальной текст здесь как примечание. В монографии как раз жирным выделено

2024-02-08 20:16 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +        Для решения этой задачи ключевое значение имеет создание удобного для этой цели способа кодирования различного вида информации в памяти компьютерной системы}
```suggestion
        Для решения этой задачи ключевое значение имеет создание удобного для этой цели способа кодирования различного вида информации в памяти компьютерной системы.}
```
Забыла точку в конце

2024-02-08 20:16 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +            \begin{scnitemize}
```suggestion
            \begin{scnitemizii}
```
или как-то так надо писать во вложенных в SCn списках, иначе отображается криво. Уточни у Ани

2024-02-08 20:18 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment1.tex
> +    \scntext{примечание}{Кибернетическая система динамически сопоставляет полученную информацию с выбранными действиями,
(здесь акцент больше на маленькую букву)

2024-02-10 21:32 UTC, MakarenkoAI commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +            \begin{scnitemize}
scnitemizeii если внутри scnitemize

2024-02-10 23:23 UTC, MakarenkoAI requested changes

2024-02-10 23:23 UTC, MakarenkoAI commented on Contents/part_intro/src/intro_hs/intro_hs_segment6.tex
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/84605fab-69c6-4c5f-8ed9-cbdac4165ce2)

2024-02-14 08:49 UTC, MksmOrlov requested changes

2024-02-14 08:49 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs.tex
> +			\scnitem{\scncite{Fry2002}}
дублируется. На две строки выше уже есть такой

2024-02-14 08:49 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment1.tex
> +        \end{scnrelfrom}
правильно будет "\scnrelfrom{первый домен}{кибернетическая система}"

2024-02-14 08:49 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +        системы}
здесь разрыв строки не надо. Одна строка должна быть. Транслятор может из-за лишних пробелов не склеить понятия

2024-02-14 08:49 UTC, MksmOrlov commented on Contents/part_intro/src/intro_hs/intro_hs_segment10.tex
> +            систем и их пользователей}
тоже поубирай пробелы лишние и пеерносы строк. И сделай scnindent, это примечание ведь к "способность к постоянному мониторингу и поддержке своей совместимости"

2024-02-14 09:13 UTC, MksmOrlov approved these changes

2024-02-14 11:07 UTC, MakarenkoAI approved these changes

2024-02-14 14:55 UTC, merged