part 1.2 Intelligent computer systems
ostis-ai/ostis-standard pull request #380
Opened 2024-01-28 15:55 UTC by PetrochukKsenija

ПР студента https://github.com/ostis-ai/ostis-standard/pull/357

2024-01-29 13:40 UTC, MakarenkoAI requested changes
1. Нужно полностью добавить Введение в главу 1.2, ничего не нашла (стр. 39-40 в монографии)
2. Не нашла
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/af16a2da-01a0-4465-b3f1-c09d8aa7ef58)
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/8bf03585-cbcc-489b-9d08-985feef12773)
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/a0ec2296-1972-49f6-a1db-dcda356dc6d5)
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/584a98c6-cc90-4b5b-a53a-63931db065e5)

2024-01-29 13:40 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment2.tex
> +        \scnitem{решатель задач интеллектуальных компьютерных систем нового поколения должен уметь решать
\scnfileitem

2024-01-29 13:40 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment2.tex
> +    \scnheader{решатель задач индивидуальной интеллектуальной компьютерной системы нового поколения}
\scnfileitem

2024-01-30 14:01 UTC, PetrochukKsenija commented on Contents/part_intro/src/sem_systems/segment1.tex
> +		\scntext{отличие}{Для каждого знания всегда известен язык, на котором это знание представлено и денотационная семантика которого задана. При этом указанный язык имеет достаточно большую семантическ
не совсем понимаю суть данного комментария. там же говориться про язык, у которого задана денотационная семантика. словосочетание "денотационная семантика" относится в языку, а если исправить, как предложено выше, то получится, что оно относится к знанию. Да и так буквально написано в монографии

2024-01-30 14:28 UTC, PetrochukKsenija commented on Contents/part_intro/src/sem_systems/segment2.tex
> +\begin{scnsubstruct}
Это я добавила в раздел "Предметная область и онтология смыслового представления информации"

2024-01-30 14:32 UTC, PetrochukKsenija commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +		\end{scnhaselementset}
его нк было, я сделала по аналогии с следует отличать*

2024-01-30 14:44 UTC, PetrochukKsenija commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \end{scnindent}
это добавлял студент, не заметила, когда проверяла. этого в целом там не должно быть

2024-01-30 14:48 UTC, PetrochukKsenija commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \end{scnrelfromlist}
оформить всё через \scntext{обеспечивается} или заменить \scnitem на \scnfileitem?

2024-01-30 14:59 UTC, PetrochukKsenija commented on Contents/part_intro/src/sem_systems/segment2.tex
> +\begin{scnsubstruct}
файл sd_sem_inf_rep.tex в строках в строках 8-60

2024-02-01 18:52 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +		\scntext{отличие}{Для каждого знания всегда известен язык, на котором это знание представлено и денотационная семантика которого задана. При этом указанный язык имеет достаточно большую семантическ
".. и его денотационная семантика", "..и денотационная семантика этого языка", например. Либо оставить как есть

2024-02-02 06:42 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \scntext{примечание}{Повышение уровня \textit{интероперабельности} интеллектуальных компьютерных систем определяет переход к \textbf{\textit{интеллектуальным компьютерным системам нового поколени
не в отдельном, но последним коммитом можно

2024-02-02 06:42 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \end{scnrelfromlist}
Аня права. scnfileitem

2024-02-02 06:43 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +        \scnfileitem{\textbf{\textit{Степень}} \textbf{\textit{конвергенции}}, унификации и стандартизации \textit{интеллектуальных компьютерных систем} и их компонентов и соответствующая этому \text
подмножество

2024-02-02 06:43 UTC, MksmOrlov commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +		\end{scnhaselementset}
scnfileitem

2024-02-09 08:13 UTC, MksmOrlov requested changes

2024-02-09 08:13 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment3.tex
> +            \scnfileitem{онтологию синтаксиса внутреннего языка смыслового преставления информации}
это хорошо, что ты хочешь формализовать это включение, но в этой ситуации неправильно. Нужно добавить эти пункты в предыдущую ссылку, которая заканчивается на "которой включает в себя:"

2024-02-09 08:13 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment3.tex
> +            \scnfileitem{онтологию синтаксиса внутреннего языка смыслового преставления информации}
либо формализовывать отдельно бз интерфейса и там уже включение будет правильным. А обрывать ссылку на "включаетв  себя:" некрасиво

2024-02-09 08:13 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment3.tex
> +            \scnfileitem{понимание принятых сообщений (их перевод на язык внутреннего смыслового представления информации
здесь тоже некрасиво отрывать двоеточие в конце ссылки. Приклей к ссылке всё это "относится"

2024-02-09 08:13 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment4.tex
здесь очень неправильно
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/18ed57b1-e67b-45ac-b5af-c61c5cb579ad)

2024-02-10 21:35 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_systems.tex
> +			задач}
душнила :)

2024-02-10 21:55 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment2.tex
> +\begin{scnsubstruct}
Да, ты права. там есть все. Только я бы соединила объекты эти под одним отношением
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/ebff640c-6784-4a8f-8536-6c3757f47d79)

2024-02-10 22:36 UTC, MakarenkoAI requested changes

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_systems.tex
>  		\scneqfile{\includegraphics{Contents/part_intro/src/images/arch.pdf}}
```suggestion
		\scnfileimage{Contents/part_intro/src/images/arch.pdf}
```
Судя по тому, что видела в стандарте, нужно через scnfileimage. Можно у @MksmOrlov спросить.
И не видела, чтобы Рис. Что-то там был оформлен как хэдер, обычно так 
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/4e92f85b-8eff-42a1-a36d-6e04f504b76b)

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment1.tex
> +        \end{scnindent}
```suggestion
        \begin{scnindent}
            \scnidtf{\textit{задачи}, \textit{методы} решения которых и/или требуемая для их решения исходная информация априори неизвестны}
        \end{scnindent}
```

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment1.tex
> +        \scnfileitem{Переход к \textit{семантическим} \textit{моделям решения задач}, в основе которых лежит учет не только синтаксических (структурных) аспектов обрабатываемой информации, но также и
```suggestion
        \scnfileitem{Переход к \textit{семантическим} \textit{моделям решения задач}, в основе которых лежит учет не только синтаксических (структурных) аспектов обрабатываемой информации, но также и \uline{семантических} (смысловых) аспектов этой информации --- \scnqqi{From data science to knowledge science}}
```
Поиском можно быстро  все ' - ' заменить на ' --- '

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment3.tex
> +        \begin{scnrelfromlist}{лежит в основе}
```suggestion
        \begin{scnrelfromlist}{принципы, лежащие в основе}
```
мб лучше так?

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment3.tex
> +            \scnfileitem{понимание принятых сообщений (их перевод на язык внутреннего смыслового представления информации
Нет правила для названий отношений, что они должны быть только в инфинитиве (и без всяких предлогов)? Например не относится*, решает*, а решение*/решать*, относиться*/отношение*/иметь связь*
Ощущение, что так можно выдумать все, что угодно, а это не правильно. Если можно сделать отношение решает*, то тогда и решают* и решаем* и т.д.

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment3.tex
> +        всего, касается формы (scnqq{синтаксической} стороны) \textit{пользовательского интерфейса}, а не смыслового содержания
```suggestion
        всего, касается формы (\scnqq{синтаксической} стороны) \textit{пользовательского интерфейса}, а не смыслового содержания
```

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +				этих описываемых сущностей.}
```suggestion
		\scntext{обусловлено}{
			\item{Каждая описываемая сущность, то есть сущность, имеющая соответствующий ей знак, может иметь неограниченное
				число связей с другими описываемыми сущностями;}
			\item{каждая описываемая сущность в смысловом представлении имеет единственный знак, так как синонимия
				знаков здесь запрещена;}
			\item{все связи между описываемыми сущностями описываются (отражаются, моделируются) связями между знаками
				этих описываемых сущностей.}
```
Тут лучше разделить единый текст на три \scnfileitem
И почему обусловлено* (обусловлена/обусловлен??) ? Я не понимаю подбор названий для отношений :*)

2024-02-10 22:36 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/bdb5ec2d-b07b-4684-9eb9-0768b789668e)
Тут бы перевести explantion

2024-02-11 20:50 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment3.tex
> +            \scnfileitem{понимание принятых сообщений (их перевод на язык внутреннего смыслового представления информации
Такие правила не формализованы. Что-то привыкли писать одинаково, а что-то пишут как хотят. Как бы там ни было, тут по смыслу криво

2024-02-19 08:19 UTC, MakarenkoAI requested changes

2024-02-19 08:19 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \scntext{примечание}{Повышение уровня \textit{интероперабельности} интеллектуальных компьютерных систем определяет переход к \textbf{\textit{интеллектуальным компьютерным системам нового поколени
```suggestion
    \scntext{примечание}{Повышение уровня \textit{интероперабельности} интеллектуальных компьютерных систем определяет переход к \textbf{\textit{интеллектуальным компьютерным системам нового поколения}}, без которых невозможна реализация таких проектов, как \textit{интеллектуальное-предприятие}, \textit{интеллектуальная-больница}, \textit{интеллектуальная-школа}, \textit{интеллектуальный-университет}, \textit{интеллектуальная-кафедра}, \textit{интеллектуальный-дом}, \textit{интеллектуальный-город}, \textit{интеллектуальное-общество}.}
```
И исправить нерезолвнутые

2024-02-20 06:36 UTC, MksmOrlov requested changes

2024-02-20 06:36 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \end{scnhaselementset}
тут без множества. Принадлежность от "характеристики" к каждой ссылке

2024-02-20 06:36 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \scniselement{функциональный аспект}
принадлежность в другую сторону. \scnhaselement

2024-02-23 13:06 UTC, PetrochukKsenija commented
Пересмотрите, пожалуйста, старые комментарии, которые не закрыты, они уже были исправлены

2024-02-23 17:47 UTC, MakarenkoAI requested changes

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_systems.tex
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/26db2d5b-3668-4ee9-88b8-dfab8855ae9c)
Нужно вписать названия

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_systems.tex
> +			интероперабельность и семантическая совместимость. В главе рассматривается подход к обеспечению ука
```suggestion
			интероперабельность и семантическая совместимость. Рассматривается подход к обеспечению ука
```

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \scnhaselement{\textbf{\textit{cемантическая совместимость}} между \textit{интеллектуальными компьютерными системами} в целом и \textit{семантическая совместимость} между компонентами каждой \tex
```suggestion
    \scnhaselement{\textbf{\textit{cтепень}} \textbf{\textit{конвергенции}}, унификации и стандартизации \textit{интеллектуальных компьютерных систем} и их компонентов и соответствующая этому \textbf{\textit{степень интеграции}} (глубина интеграции) \textit{интеллектуальных компьютерных систем} и их компонентов.}
    \scnhaselement{\textbf{\textit{cемантическая совместимость}} между \textit{интеллектуальными компьютерными системами} в целом и \textit{семантическая совместимость} между компонентами каждой \textit{интеллектуальной компьютерной системы} (в частности, совместимость между различными \textit{видами знаний} и различными \textit{моделями обработки знаний}), которые являются основными показателями степени \textbf{\textit{конвергенции}} (сближения) между \textit{интеллектуальными компьютерными системами} и их компонентами.}
```
слишком для ноды. Пусть Максим подскажет как тут лучше

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sem_systems/segment4.tex
> +    \scnheader{принципы, лежащих в основе интеллектуальных компьютерных систем нового поколения}
```suggestion
    \scnheader{принципы, лежащие в основе интеллектуальных компьютерных систем нового поколения}
```

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +			(согласованность) и требует дополнительных усилий на ее восстановление}
```suggestion
			\scnitem{методы и средства постоянного мониторинга и восстановления совместимости в условиях интенсивной
			эволюции компьютерных систем и их пользователей, которая часто нарушает достигнутую совместимость
			(согласованность) и требует дополнительных усилий на ее восстановление}
```
такая же ситуация, слишком для ноды

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +		\scnheader{обеспечения совместимости различных видов знаний, различных моделей решения задач и различных компьютерных систем}
```suggestion
		\scnheader{обеспечение совместимости различных видов знаний, различных моделей решения задач и различных компьютерных систем}
```
мб лучше убрать обеспечение вообще

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +			промежуточное дело.>> (\scncite{Melchuk}).}
```suggestion
			промежуточное дело.>> (\scncite{Melchuk}).}
```
тут везде вынести ссылки

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +				\scnrelto{ключевой знак}{\scncite{Martynov1984}}
```suggestion
				\scnrelfrom{ключевой знак}{\scncite{Martynov1984}}
```

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/714a1b41-ce3f-4218-8d48-25ca204a8298)
from, not to
change everywhere

2024-02-23 17:47 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +				\textit{представления знаний}, не используемой на практике. \scncite{Inform2008}
\scncite{Inform2008} remove this everywhere and add it with relation

2024-02-23 18:11 UTC, MksmOrlov commented on Contents/part_intro/src/sem_systems/segment1.tex
> +    \scnhaselement{\textbf{\textit{cемантическая совместимость}} между \textit{интеллектуальными компьютерными системами} в целом и \textit{семантическая совместимость} между компонентами каждой \tex
нормально, пускай будет как есть. Если что, автор сам придумает название покороче, если нужно

2024-02-23 18:11 UTC, MksmOrlov commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +			(согласованность) и требует дополнительных усилий на ее восстановление}
нормалёк

2024-02-23 18:12 UTC, MksmOrlov commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +				\scnrelto{ключевой знак}{\scncite{Martynov1984}}
в монографии было наоборот (как у Ксюши). Пусть останется как в моне, хотя мне больше нравится твоё предложение

2024-02-23 18:14 UTC, MksmOrlov approved these changes

2024-02-23 20:19 UTC, MakarenkoAI approved these changes

2024-02-25 19:53 UTC, merged