Feat/specification
ostis-ai/ostis-standard pull request #386
Opened 2024-02-08 15:04 UTC by MakarenkoAI

2024-02-09 07:51 UTC, MksmOrlov requested changes

2024-02-10 22:42 UTC, MakarenkoAI commented on specification.scs
> +      *);
я это фиксить буду, сейчас нужно проверить, чтобы мк скачивал стандарт. я для этого ПР делала

2024-02-10 22:42 UTC, MakarenkoAI commented on translated_scs/part_methods_tools/specification.scs
> +        *);
и так хватит

2024-02-16 18:21 UTC, NikitaZotov requested changes

2024-02-16 18:21 UTC, NikitaZotov commented on specification.scs
> +      *);
```suggestion
    => nrel_authors: {
          Golenkov;
          Guliakina;
          Shunkevich
      };
```

2024-02-16 18:21 UTC, NikitaZotov commented on specification.scs
> +      *);
Replace it, please, everywhere

2024-02-17 16:21 UTC, NikitaZotov approved these changes

2024-02-18 19:51 UTC, MksmOrlov approved these changes

2024-02-18 20:15 UTC, merged