Mono platform
ostis-ai/ostis-standard pull request #389
Opened 2024-02-14 20:56 UTC by MksmOrlov

Монография страница 555

2024-02-15 09:49 UTC, MakarenkoAI requested changes

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +	\scntext{примечание}{Явное выделение \textit{sc-модели базы знаний}, \textit{sc-модели решателя задач} и \textit{sc-модели интерфейса кибернетической системы} в рамках \textit{sc-модели кибернетичес
```suggestion
\begin{scnindent}
	\scntext{примечание}{Явное выделение \textit{sc-модели базы знаний}, \textit{sc-модели решателя задач} и \textit{sc-модели интерфейса кибернетической системы} в рамках \textit{sc-модели кибернетической системы} является в известной мере условным, поскольку для обеспечения платформенной независимости \textit{sc-модели кибернетической системы} и \textit{решатель задач}, и \textit{интерфейс системы} описываются средствами \textit{SC-кода} и, таким образом, тоже являются частью \textit{базы знаний}. Такое явное выделение указанных компонентов обусловлено удобством проектирования и сопровождения системы.}
\end{scnindent}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +	\scntext{примечание}{Важно отметить, что универсальность конкретного варианта реализации \textit{ostis-платформы} очевидно ограничивается физической (аппаратной) частью этой реализации. Например, ес
```suggestion
	\scntext{примечание}{Важно отметить, что универсальность конкретного варианта реализации \textit{ostis-платформы} очевидно ограничивается физической (аппаратной) частью этой реализации. Например, если аппаратная часть выбранного варианта платформы представляет собой обычный персональный компьютер, то без добавления дополнительных аппаратных компонентов система не сможет решать задачи, связанные с физическим перемещением себя и других объектов в пространстве, даже если программная часть системы способна выполнить необходимые расчеты. Говоря другими словами, любая \textit{ostis-платформа} всегда будет ограничена в решении \textit{поведенческих задач} каких-либо классов, какими бы мощными физическими ресурсами она не обладала. Таким образом, корректнее говорить об \uline{универсальности \textit{ostis-платформы} в контексте решения \textit{информационных задач}}, то есть возможности интерпретировать любые \textit{sc-модели кибернетических систем} независимо от того, какого рода \textit{информационные задачи} решают эти системы.}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scntext{примечание}{Потенциально можно говорить о нескольких возможных функционально эквивалентных вариантах \textit{scp-машины}, которые будут соответствовать разным вариантам базового языка прог
```suggestion
		\scntext{примечание}{Потенциально можно говорить о нескольких возможных функционально эквивалентных вариантах \textit{scp-машины}, которые будут соответствовать разным вариантам базового языка программирования. В рамках текущей версии \textit{Технологии OSTIS} фиксируется как денотационная семантика \textit{Языка SCP}, так и его операционная семантика, реализуемая в виде \textit{Абстрактной scp-машины}. Более подробно об этом говорится в \textit{Предметной области и онтологии Базового языка программирования ostis-систем}.}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
```suggestion
\begin{scnitemize}
		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
\end{scnitemize}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_interpreters.tex
> +        \scnidtf{Предметная область и онтология аппаратных и программных платформ реализации интеллектуальных компьютерных систем новогопоколения}
```suggestion
        \scnidtf{Предметная область и онтология аппаратных и программных платформ реализации интеллектуальных компьютерных систем нового поколения}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_interpreters_segments/segment_platfrom_independent.tex
> +				\scnfileitem{Этап реализации, то есть непосредственно воплощения разработанной модели с использованием конкретных средств (инструментов, материалов, комплектующих и так далее). В случае компьютер
```suggestion
				\scnfileitem{Этап реализации, то есть непосредственно воплощения разработанной модели с использованием конкретных средств (инструментов, материалов, комплектующих и так далее). В случае компьютерных систем выполнение данного этапа обычно предполагает выбор конкретных языков программирования, библиотек, сторонних средств, таких как с.у.б.д. и различных сервисов, а также собственно программирование и отладку системы с использованием выбранных средств.}
```

2024-02-15 09:49 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_interpreters_segments/segment_platfrom_independent.tex
> +			\scntext{примеры}{Среди популярных средств реализующих данный подход можно указать средства виртуализации (VirtualBox, DosBox, VMWare Workstation), контейнеризации (Docker), эмуляции приложений An
```suggestion
			\scntext{примеры}{Среди популярных средств, реализующих данный подход можно указать средства виртуализации (VirtualBox, DosBox, VMWare Workstation), контейнеризации (Docker), эмуляции приложений Android для настольных операционных систем (Genymotion, Bluestacks, Anbox) и многие другие.}
```

2024-02-15 10:33 UTC, MksmOrlov commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +	\scntext{примечание}{Явное выделение \textit{sc-модели базы знаний}, \textit{sc-модели решателя задач} и \textit{sc-модели интерфейса кибернетической системы} в рамках \textit{sc-модели кибернетичес
не уверен, что такое будет транслироваться. Если хочешь примечание ко множеству, то нужно eqtoset

2024-02-15 10:33 UTC, MksmOrlov commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
зачем itemize для одной сущности?

2024-02-15 13:50 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
Смотрите* разве не к примечанию?

2024-02-15 13:53 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
Scnindent, перепутала

2024-02-15 13:54 UTC, MksmOrlov commented on Contents/part_platform/src/sd_method_prod_sys.tex
> +		\scnrelfrom{смотрите}{Предметная область и онтология Базового языка программирования ostis-систем}
это к понятию scp-машина

2024-02-15 18:27 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_interpreters_segments/segment_ostis_platform.tex
> +			\item{\textit{Являются многократно используемым компонентом ostis-систем} и специфицируются в рамках соответствующих библиотек.}
```suggestion
			\item{Являются \textit{многократно используемым компонентом ostis-систем} и специфицируются в рамках соответствующих библиотек.}
```

2024-02-15 19:35 UTC, MakarenkoAI approved these changes

2024-02-16 10:07 UTC, NikitaZotov commented on Contents/part_platform/src/sd_interpreters.tex
> +        \input{Contents/part_platform/src/sd_interpreters_segments/segment_ostis_platform}
```suggestion
\input{Contents/part_platform/src/sd_interpreters_segments/segment_ostis_platform}
```

2024-02-16 18:33 UTC, NikitaZotov approved these changes

2024-02-16 18:44 UTC, merged