Mono logic formalisation
ostis-ai/ostis-standard pull request #390
Opened 2024-02-15 19:27 UTC by MksmOrlov

Страница монографии 221

2024-02-15 19:56 UTC, MakarenkoAI requested changes

2024-02-15 19:56 UTC, MakarenkoAI commented on Contents/biblio/biblio.bib
> +	title        = {Модели и алгоритмы интеграции знаний на основе однородных семантических сетей (дисс. на соисвание степени канд. техн. наук: 05.13.17)},
```suggestion
	title        = {Модели и алгоритмы интеграции знаний на основе однородных семантических сетей (дисс. на соискание степени канд. техн. наук: 05.13.17)},
```

2024-02-15 19:56 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +    	\scntext{аннотация}{В главе рассмотрено представление логических формул и высказываний как для классических логик и их приложений (прикладных логик), так и представление некоторых понятий неклас
```suggestion
    	\scntext{аннотация}{В предметной области рассмотрено представление логических формул и высказываний как для классических логик и их приложений (прикладных логик), так и представление некоторых понятий неклассических логик.}
```

2024-02-15 19:56 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
почему невозможно?

2024-02-15 19:56 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{определение}{\textbf{\textit{квантор}} — это \textit{отношение}, каждая связка которого истинна (или имеет истинную интерпретацию) при выполнении дополнительных условий, связанных с
```suggestion
        \scntext{определение}{\textbf{\textit{квантор}} --- это \textit{отношение}, каждая связка которого истинна (или имеет истинную интерпретацию) при выполнении дополнительных условий, связанных с некоторыми из переменных, входящих в состав \textit{логических формул}, входящих в ее состав.}
```

2024-02-15 19:56 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \end{SCn}
зачем 
```suggestion
    
        	\scnheader{слотовое бинарное отношение}
        	\scnnote{Слотовое бинарное отношение --- слотовое sc-отношение, являющееся множеством.}

```

2024-02-15 20:00 UTC, MksmOrlov commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
потому что пытаешься установить истинность того, чего не знаешь, не понимаешь.

2024-02-15 20:13 UTC, MksmOrlov commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \end{SCn}
копипаст из монографии. Это ни на что не влияет. А убирать это потратить драгоценные минуты

2024-02-16 05:17 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \end{SCn}
Я за то, чтобы удалить.

2024-02-16 05:19 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
Я бы оставила как было

2024-02-16 06:21 UTC, MakarenkoAI requested changes

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        	\scnnote{Иррефлексивное слотовое бинарное отношение --- слотовое (бинарное) отношение, любая связка которого не является связкой,обозначенной петлевой дугой (дугой с совпадающим началом и ко
```suggestion
        	\scnnote{Иррефлексивное слотовое бинарное отношение --- слотовое (бинарное) отношение, любая связка которого не является связкой, обозначенной петлевой дугой (дугой с совпадающим началом и концом).}
```

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        	\scnnote{Транзитивное слотовое бинарное отношение --- слотовое бинарное отношение, для любых двух связок которого, конец одной из которых является началом второй, существует связка началом к
```suggestion
        	\scnnote{Транзитивное слотовое бинарное отношение --- слотовое бинарное отношение, для любых двух связок которого, конец одной из которых является началом второй, существует связка, началом которой является начало первой связки, а концом является конец второй связки.}
```

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        	\scnnote{Монотонное неслотовое бинарное отношение* --- неслотовое бинарное отношение по отношению к отношению порядка, для которого существует ролевое отношение, первым доменом которого явля
```suggestion
        	\scnnote{Монотонное неслотовое бинарное отношение* --- неслотовое бинарное отношение по отношению к отношению порядка, для которого существует ролевое отношение, первым доменом которого является это бинарное отношение, такое, что если есть связка этого бинарного отношения, то для любой его связки элемент, принадлежащий ей под этим ролевым отношением, в отличие от другого связан связкой этого отношения порядка с элементом, принадлежащим первой связке под этим же ролевым отношением, в отличие от другого элемента первой связки, найдется третья связка бинарного отношения такая, что элемент, принадлежащий ей под ролевым отношением, принадлежит под этим же ролевым отношением второй связке, а элемент, принадлежащий не под ролевым отношением третьей связке, принадлежит не под ролевым отношением первой связке.}
```
я пыталась понять, не получилось

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        	\scnheader{Отношение выводимости}
```suggestion
        	\scnheader{отношение выводимости}
```
зачем с прописной?

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        		\scnnote{\textbf{\textit{конструктивно истинное высказывание*}} --- подмножество \textit{истинного высказывания*}.
раздели на несколько примечаний, читать невозможно

2024-02-16 06:21 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        		\scnnote{\textit{нечеткая истинность*} связывает конечное sc-множество с временными принадлежностями на конечном множестве конечных явлений принадлежности с высказыванием. На явлениях прина
```suggestion
        		\scnnote{\textit{нечеткая истинность*} связывает конечное sc-множество с временными принадлежностями на конечном множестве конечных явлений принадлежности с высказыванием. На явлениях принадлежности задано конечное sc-подмножество sc-отношения становления (непосредственно прежде, непосредственно после), которое задает структуру соответствующих sc-подмножеств. Эта структура является ориентированным деревом. \textit{нечеткая истинность*} --- \textit{бинарное отношение} между (нечеткой) принадлежностью связки  \textit{высказывания} \textit{формальной теории} и конечного sc-множества и действительным числом от 0.0 до 1.0. Нечеткая истинность отрицания высказывания равна разности 1.0 и нечеткой истинности высказывания, принадлежащего отрицанию. \textit{нечеткая истинность*} \textit{конъюнкции*} высказываний не превышает минимума нечеткой истинности элементов этой конъюнкции и не ниже (граничного или драстического) произведения \textit{нечеткой истинности*} этих же элементов конъюнкции. \textit{нечеткая истинность*} \textit{дизъюнкции*} не превышает (граничной или драстической) суммы \textit{нечеткой истинности*} элементов этой конъюнкции и не ниже максимума нечеткой истинности этих же элементов конъюнкции. \textit{нечеткая истинность*} \textit{атомарных высказываний} равна среднему арифметическому изоморфного вложения структуры \textit{высказывания} в каждое из sc-подмножеств конечного sc-множества, которые входят в структуру заданную sc-отношением становления.}
```
\textit{нечеткая истинность*} --- \textit{бинарное отношение} между (нечеткой) принадлежностью связки  \textit{высказывания} \textit{формальной теории} и конечного sc-множества и действительным числом от 0.0 до 1.0.

можно в определение вынести

2024-02-16 07:16 UTC, kilativ-dotcom commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
к этому куску у меня давно был вопрос
как быть с (A\/(!A))? его же можно решить не зная что за А такой

2024-02-16 08:06 UTC, kilativ-dotcom commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
(A\\/(!A)

2024-02-16 08:06 UTC, MksmOrlov commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
Это смотря в какой логике. И может быть бессмысленным высказыванием

2024-02-16 08:08 UTC, MksmOrlov commented on Contents/part_kb/src/sd_logical_formulas.tex
> +        \scntext{примечание}{Следует отметить, что невозможно говорить об истинности либо ложности \textbf{\textit{неатомарного высказывания}} в рамках какой-либо \textit{формальной теории}, в случае
В любом случае, этот спор больше к содержательной части, по которой должны работать авторы материала. А суть ПРа в переносе. Можно уточнить у Ивашенко как у автора именно этого изменения

2024-02-17 15:14 UTC, MakarenkoAI requested changes

2024-02-18 18:22 UTC, MksmOrlov commented on Contents/part_kb/src/sd_logical_formulas.tex
>          \scnheader{аксиома\scnrolesign}
аксиома и теорема - это относительные понятия, они в стандарте есть

2024-02-18 18:47 UTC, MakarenkoAI approved these changes

2024-02-18 20:16 UTC, NikitaZotov approved these changes

2024-02-18 20:26 UTC, merged