Mono sem comp
ostis-ai/ostis-standard pull request #391
Opened 2024-02-16 20:53 UTC by MksmOrlov

2024-02-18 20:39 UTC, NikitaZotov requested changes

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform.tex
>  \scsubsubsection[
\protect\scneditors{Голенков В.В;Шункевич Д.В.;Гулякина Н.А.;Ивашенко В.П.;Захарьев В.А.}

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform.tex
> +    \protect\scneditors{Голенков В.В;Шункевич Д.В.;Гулякина Н.А.;Ивашенко В.П.;Захарьев В.А.;Корончик Д.Н.;Марковец В.С.;Зотов Н.В.}
```suggestion
    \protect\scneditors{Шункевич Д.В.;Зотов Н.В.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform.tex
> +%\input{Contents/part_platform/src/sd_program_interp.tex}
```suggestion
\input{Contents/part_platform/src/sd_program_interp.tex}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform.tex
> +%\input{Contents/part_platform/src/sd_method_prod_sys.tex}
```suggestion
\input{Contents/part_platform/src/sd_method_prod_sys.tex}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform.tex
> +%\input{Contents/part_platform/src/sd_interpreters.tex}
```suggestion
\input{Contents/part_platform/src/sd_interpreters.tex}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
> +		\scnfileitem{1984 год --- в Московском  институте электронной техники В.В. Голенковым защищена кандидатского диссертация на тему \scnqq{Структурная организация и переработка информации в электронны
```suggestion
		\scnfileitem{1984 год --- в Московском институте электронной техники В.В. Голенковым защищена кандидатского диссертация на тему \scnqq{Структурная организация и переработка информации в электронных математических машинах, управляемых потоком сложноструктурированных данных}, в которой были сформулированы и рассмотрены основные принципы семантических ассоциативных компьютеров.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +	\scnnote{Для определения базовой структуры \textit{ассоциативного семантического компьютера} уточним варианты такой структуры, предложенные в работах В.В. Голенкова и В.М. Кузьмицкого. В частности,
```suggestion
	\scnnote{Для определения базовой структуры \textit{ассоциативного семантического компьютера} уточним варианты такой структуры, предложенные в работах В.В. Голенкова и В.М. Кузьмицкого. В частности, в работе В.М. Кузмицкого предложен переход от крупнозернистых архитектур графодинамических машин к мелкозернистым.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +	\scnnote{Для определения базовой структуры \textit{ассоциативного семантического компьютера} уточним варианты такой структуры, предложенные в работах В.В. Голенкова и В.М. Кузьмицкого. В частности,
```suggestion
	\scnnote{Для определения базовой структуры \textit{ассоциативного семантического компьютера} уточним варианты такой структуры, предложенные в работах В.В. Голенкова и В.М. Кузьмицкого. В частности, в работе В.М. Кузьмицкого предложен переход от крупнозернистых архитектур графодинамических машин к мелкозернистым.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +	\scnnote{Целесообразность перехода от крупнозернистых архитектур к мелкозернистым обусловлена  соответствующим увеличением степени потенциального параллелизма в процедурах переработки знаний.}
```suggestion
	\scnnote{Целесообразность перехода от крупнозернистых архитектур к мелкозернистым обусловлена соответствующим увеличением степени потенциального параллелизма в процедурах переработки знаний.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +		\scnfileitem{Модуль памяти (реализация \textit{sc-памяти}) представляет собой множество ячеек, каждая из которых может хранить некоторый sc-элемент или может быть пустой. Каждая ячейка такой памяти
```suggestion
		\scnfileitem{Модуль памяти (реализация \textit{sc-памяти}) представляет собой множество ячеек, каждая из которых может хранить некоторый sc-элемент или может быть пустой. Каждая ячейка такой памяти имеет некоторый уникальный внутренний адрес, аналогичный адресу ячеек фон-Неймановской памяти. В то же время, при обработке информации, хранимой в такой памяти, на уровне языка команд (Языка SCP), в отличие от фон-Неймановской памяти адреса ячеек не учитываются, доступ к sc-элементам осуществляется исключительно по связям инцидентности между ними. Исключение составляют некоторые ключевые sc-элементы, набор которых оговаривается отдельно и доступ к которым осуществляется по какому-либо другому идентификатору, например, системному sc-идентификатору или основному sc-идентификатору для какого-либо внешнего языка, но не по адресу. 
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +		\scnfileitem{В рамках предложенной мелкозернистой архитектуры, в отличие от крупнозернистой, нет необходимости создания копий sc-элементов, и разработки специальных языков кодирования для полученны
```suggestion
		\scnfileitem{В рамках предложенной мелкозернистой архитектуры, в отличие от крупнозернистой, нет необходимости создания копий sc-элементов, и разработки специальных языков кодирования для полученных конструкций, таких как \textit{SCD-код}, поскольку каждый процессорный элемент хранит один атомарный фрагмент всей хранимой sc-конструкции и число логических связей с другими процессорными элементами не ограничено.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +			\scnfileitem{Если число логических связей между элементами sc-конструкции не превышает числа доступных физических каналов связи процессорного элемента и sc-граф является планарным (хоть sc-граф не
```suggestion
			\scnfileitem{Если число логических связей между элементами sc-конструкции не превышает числа доступных физических каналов связи процессорного элемента и sc-граф является планарным (хоть sc-граф не является классическим графом, можно говорить о его планарности по аналогии с планарностью классических графов), то возможна запись sc-конструкции в процессоро-память таким образом, чтобы конфигурация \textit{логических каналов связи} взаимно однозначно соответствовала какому-то подмножеству физических каналов связи. Таким образом, актуальной является разработка алгоритмов оптимальной \scnqq{укладки} sc-графов в процессоро-память для обеспечения последующей эффективности передачи сообщений между процессорными элементами.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_principles.tex
> +		\scnfileitem{Процессор и память \textit{ассоциативного семантического компьютера} глубоко интегрированы и составляют единую процессоро-память. Процессор \textit{ассоциативного семантического компью
```suggestion
		\scnfileitem{Процессор и память \textit{ассоциативного семантического компьютера} глубоко интегрированы и составляют единую процессоро-память. Процессор \textit{ассоциативного семантического компьютера} равномерно \scnqq{распределен} по его памяти так, что процессорные элементы одновременно являются и элементами памяти компьютера. То есть каждая ячейка дополняется функциональным (процессорным) элементом, a перестраиваемые связи между ячейками становятся коммутируемыми каналами связи между процессорными элементами. Каждый процессорный элемент при этом имеет свою специальную внутреннюю регистровую память, отражающую важные для данного процессорного элемента аспекты текущего состояния процесса выполнения элементарных операций языка микропрограмм, обеспечивающих интерпретацию языка более высокого уровня (Языка SCP).}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +				\item{В \textit{Язык SCPD} встроены средства, позволяющие распознавать \scnqq{свой"} и \scnqq{чужой} комбинированный модуль, для этого вводятся операторы работы с идентификаторами модулей;}
```suggestion
				\item{В \textit{Язык SCPD} встроены средства, позволяющие распознавать \scnqq{свой} и \scnqq{чужой} комбинированный модуль, для этого вводятся операторы работы с идентификаторами модулей;}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +		\scnfileitem{Процессоро-память \textit{ассоциативного семантического компьютера} состоит из однотипных модулей, которые будем называть процессорными элементами sc-памяти или просто \textit{процессо
```suggestion
		\scnfileitem{Процессоро-память \textit{ассоциативного семантического компьютера} состоит из однотипных модулей, которые будем называть процессорными элементами sc-памяти или просто \textit{процессорными элементами}. Каждый \textit{процессорный элемент} соответствует одному sc-элементу (хранит один sc-элемент). При этом в каждый момент времени каждый \textit{процессорный элемент} может быть пустым (не хранить никакой sc-элемент) или заполненным, то есть иметь взаимно однозначно соответствующий ему хранимый sc-элемент. На физическом уровне для описания этого факта вводится соответствующий признак, имеющим два значения. Таким образом, каждый \textit{процессорный элемент} \scnqq{отвечает} только за один sc-элемент и, в отличие от крупнозернистого варианта архитектуры \textit{ассоциативного семантического компьютера}, \uline{задача не может быть решена} \uline{одним \textit{процессорным элементом}} и количество таких \textit{процессорных элементов} достаточно велико (соответствует максимальному возможному числу sc-элементов, хранимых в базе знаний некоторой ostis-системы). Опыт разработки прикладных ostis-систем показывает, что в среднем число sc-элементов в базе знаний такой ostis-системы составляет от нескольких сотен тысяч до нескольких миллионов. Ситуация, когда в рамках процессоро-памяти необходимо представить sc-конструкцию, число элементов которой больше числа \textit{процессорных элементов} на данный момент не рассматривается и требует дополнительного исследования.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +			\scnfileitem{Язык SCP, не зависящий от реализации ostis-платформы, на котором пишутся программы sc-агентов обработки знаний. Язык SCP является "водоразделом"{} между платформенно-зависимой частью
```suggestion
			\scnfileitem{Язык SCP, не зависящий от реализации ostis-платформы, на котором пишутся программы sc-агентов обработки знаний. Язык SCP является \scnqq{водоразделом} между платформенно-зависимой частью и платформенно-независимой частью ostis-системы, таким образом, он является самым низкоуровневым языком среди всех возможных платформенно-независимых языков, и одновременно языком высокого уровня с точки зрения ostis-платформы.}
```

2024-02-18 20:39 UTC, NikitaZotov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +		\scnfileitem{Расширяемость архитектуры позволяет легко наращивать число процессорных элементов без существенного снижения производительности, поскольку в предложенной архитектуре нет явно выделяемы
### 
```suggestion
		\scnfileitem{Расширяемость архитектуры позволяет легко наращивать число процессорных элементов без существенного снижения производительности, поскольку в предложенной архитектуре нет явно выделяемых процессорных модулей и накопительных модулей, соответственно исключается необходимость передачи информации между такими модулями, кроме того процессорный модуль перестает быть разделяемым ресурсом для большого числа одновременно выполняемых процессов. Все перечисленное позволит в конечном итоге решить проблему, известную как проблема \scnqq{бутылочного горлышка} архитектуры фон Неймана.}
```

2024-02-18 21:05 UTC, MksmOrlov commented on Contents/part_platform.tex
>  \scsubsubsection[
нет, авторов мы договорились в самом конце вписывать по всем ПрО. Просто скопировать из монографии не получится

2024-02-18 21:05 UTC, MksmOrlov commented on Contents/part_platform.tex
> +    \protect\scneditors{Голенков В.В;Шункевич Д.В.;Гулякина Н.А.;Ивашенко В.П.;Захарьев В.А.;Корончик Д.Н.;Марковец В.С.;Зотов Н.В.}
нет, авторов мы договорились в самом конце вписывать по всем ПрО. Просто скопировать из монографии не получится

2024-02-18 21:07 UTC, MksmOrlov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +	\scnnote{Для определения базовой структуры \textit{ассоциативного семантического компьютера} уточним варианты такой структуры, предложенные в работах В.В. Голенкова и В.М. Кузьмицкого. В частности,
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/96a771a3-e1d3-4e7b-ad36-dc4088815836)

2024-02-19 13:56 UTC, MakarenkoAI requested changes

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp.tex
> +    	\scntext{аннотация}{В главе рассмотрены принципы реализации аппаратной платформы для реализации систем, построенных на основе Технологии OSTIS, --- ассоциативного семантического компьютера.}
```suggestion
    	\scntext{аннотация}{В предметной области рассмотрены принципы реализации аппаратной платформы для реализации систем, построенных на основе Технологии OSTIS, --- ассоциативного семантического компьютера.}
```

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp.tex
> +    		\scnfileitem{В предметной области и онтолгии рассмотрены недостатки доминирующей в настоящее время фон-Неймановской архитектуры компьютерных систем в качестве основы для построения интеллектуал
```suggestion
    		\scnfileitem{В предметной области и онтологии рассмотрены недостатки доминирующей в настоящее время фон-Неймановской архитектуры компьютерных систем в качестве основы для построения интеллектуальных компьютерных систем нового поколения, проведен анализ современных подходов к разработке аппаратных архитектур, устраняющих некоторые из указанных недостатков, обоснована необходимость разработки принципиально новых аппаратных архитектур, представляющих собой аппаратный вариант реализации ostis-платформ --- \textit{ассоциативных семантических компьютеров}.}
```

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
> +		\scnfileitem{каждая конкретная операция (команда), выполняемая в памяти, представляется (специфицируется) в памяти в виде строки, состоящей
```suggestion
		\scnfileitem{Каждая конкретная операция (команда), выполняемая в памяти, представляется (специфицируется) в памяти в виде строки, состоящей
```

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
> +	\scnhaselement{системы, осуществляющие переработку информации непосредственно в памяти путем равномерного распределения функциональных средств по памяти и, в частности, предложенная М. Н. Вайнцвайго
```suggestion
	\scnhaselement{системы, осуществляющие переработку информации непосредственно в памяти путем равномерного распределения функциональных средств по памяти и, в частности, предложенная М. Н. Вайнцвайгом процессоро-память, ориентированная на решение задач Искусственного интеллекта}
```
слишком для ноды

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
> +	\scnhaselement{активные семантические сети (М-сети)}
```suggestion
	\scnhaselement{активные семантические сети (М-сети)}
```
М-сети можно в scnidtf

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
Нужно определиться как писать фон Нейман или фон-Нейман, пересмотри по всем ПрО

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_comp_arch_analysis.tex
> +			\scnnote{Примером такой архитектуры является клеточный автомат (см. \scncite{Wolfram2002}). Элементарные клеточные (двоичные) автоматы разделяются на: быстро переходящие в однородное состояние (со
```suggestion
			\scnnote{Примером такой архитектуры является клеточный автомат. Элементарные клеточные (двоичные) автоматы разделяются на: быстро переходящие в однородное состояние (состояние только из нулей или единиц); быстро переходящие в устойчивое или циклическое состояние; остающиеся в хаотическом (случайном) состоянии; образующие как области с устойчивым или циклическим состоянием, так и области, в которых проявляются сложные взаимодействия элементов состояний, вплоть до Тьюринг-полных.
```
вынеси, пожалуйста

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_comp_arch_analysis.tex
> +			Обработка информации с помощью клеточных автоматов позволяет строить вычислительные системы в том числе с перестраиваемой (в том числе фрактало-подобной) структурой на основе локальных параллельно
```suggestion
			\\Обработка информации с помощью клеточных автоматов позволяет строить вычислительные системы в том числе с перестраиваемой (в том числе фрактало-подобной) структурой на основе локальных параллельно (конкурентно) выполняемых несложных правил. Существуют разновидности клеточных автоматов, поддерживающих необратимые, обратимые, детерминированные, недетерминированные, специализированные, универсальные (в том числе Тьюринг-полные) вычисления. Работа клеточных автоматов напоминает волновые процессы распространяющиеся в среде элементов состояния клеточного автомата.}
```

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_principles.tex
> +	\scntext{примечание}{На данном этапе работы были выявлены несколько основных вариантов вариантов архитектуры \textit{ассоциативных семантических компьютеров}. В основу предлагаемого подхода к разраб
```suggestion
	\scntext{примечание}{Были выявлены несколько основных вариантов вариантов архитектуры \textit{ассоциативных семантических компьютеров}. В основу предлагаемого подхода к разработке \textit{ассоциативного семантического компьютера} положены идеи, предложенные в работах В.В. Голенкова и получившие развитие в работе В.М. Кузьмицкого.}
```
Сейчас понятно на каком этапе (или нет)
А через 10 лет будет непонятно

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_principles.tex
> +	\scnheader{ассоциативный семантический компьютер}
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/8e632b15-6b65-45ac-a6f0-11bcc7bca049)
забыл ссылку на ПрО

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +				\item{перечень связей инцидентности данного sc-элемента с другими sc-элементами, что фактически означает хранение набора адресов ячеек памяти, соответствующих sc-элементам, инцидентным данному sc
![image](https://github.com/ostis-ai/ostis-standard/assets/90891293/31b1fb8e-0ca0-43f8-bbf0-1e253a5374fc)
ссылка

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +				\item{\textit{логические каналы связи} между процессорными элементами формируются динамически и соответствуют \textit{связям инцидентности} между sc-элементами. Таким образом, \textit{логические
![Uploading image.png…]()
забыл

2024-02-19 13:56 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +				\item{Кроме связей инцидентности \textit{логические каналы связи} могут соответствовать и другим типам связей между sc-элементами, по аналогии с тем, как это сделано в программном варианте реализ
![Uploading image.png…]()

забыл

2024-02-19 19:30 UTC, MksmOrlov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_arch.tex
> +				\item{перечень связей инцидентности данного sc-элемента с другими sc-элементами, что фактически означает хранение набора адресов ячеек памяти, соответствующих sc-элементам, инцидентным данному sc
Есть выше. А тут много пунктов, а ссылку надо только к одному, поэтому не надо

2024-02-19 19:55 UTC, MksmOrlov commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_principles.tex
> +	\scntext{примечание}{На данном этапе работы были выявлены несколько основных вариантов вариантов архитектуры \textit{ассоциативных семантических компьютеров}. В основу предлагаемого подхода к разраб
данный этот тот, который в котором ты читаешь этот текст. Когда придумают новые варианты архитектур, их добавят сюда

2024-02-19 20:00 UTC, NikitaZotov approved these changes

2024-02-19 20:08 UTC, MakarenkoAI commented on Contents/part_platform/src/sd_sem_comp/segment_sem_comp_analysis.tex
> +	\scnhaselement{системы, осуществляющие переработку информации непосредственно в памяти путем равномерного распределения функциональных средств по памяти и, в частности, предложенная М. Н. Вайнцвайго
предлагаю после частности всё вынести в примечание, или разбить на две ноды и сделать объединение
или оставить авторам, как хочешь

2024-02-19 20:16 UTC, MakarenkoAI approved these changes

2024-02-19 20:21 UTC, merged