fix: sd_lang
ostis-ai/ostis-standard pull request #392
Opened 2024-02-17 22:41 UTC by MakarenkoAI

Part 2.3

2024-02-18 13:07 UTC, NikitaZotov requested changes

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_idtf.tex
>                  \begin{scnhaselementrolelist}{пример}%some problems here
```suggestion
                \begin{scnhaselementrolelist}{пример}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_idtf.tex
> +                        \\Кроме того, следует помнить, что \uline{далеко не все} \textit{sc-элементы}, входящие в состав базы знаний ostis-системы, должны иметь соответствующие им sc-идентификаторы (
```suggestion
                        \\Кроме того, следует помнить, что \uline{далеко не все} \textit{sc-элементы}, входящие в состав базы знаний ostis-системы, должны иметь соответствующие им sc-идентификаторы (быть идентифицированными). Стоит подчеркнуть то, что далеко не все sc-элементы должны иметь \textit{простые sc-идентификаторы} по той простой причине, что для многих sc-элементов в случае необходимости можно достаточно легко построить идентифицирующее их \textit{sc-выражение} (sc-выражение). Тем не менее, для целого ряда сущностей (например, для понятий, исторических событий и т.п.) обойтись без простых sc-идентификаторов очень сложно.
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scg.tex
>              \item все sc.g-узлы изображаются, как и ранее, \uline{плоскими} графическими примитивами. При изменении точки просмотра они \uline{всегда} поворачиваются\ параллельно плоскости экрана, но
```suggestion
            \item все sc.g-узлы изображаются, как и ранее, \uline{плоскими} графическими примитивами. При изменении точки просмотра они \uline{всегда} поворачиваются\ параллельно плоскости экрана, но их масштаб (размер на экране) при удалении от точки просмотра \uline{уменьшается};
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scg.tex
> +            	\\\textit{Переменная постоянная сущность первого уровня } (первичная sc-переменная), не являющаяся бинарной связью --- это переменная, каждым значением которой является \textit{константн
```suggestion
            	\\\textit{Переменная постоянная сущность первого уровня} (первичная sc-переменная), не являющаяся бинарной связью --- это переменная, каждым значением которой является \textit{константная постоянная сущность}, не являющаяся бинарной связью. Такая переменная изображается квадратиком, который ориентирован по вертикали и горизонтали.
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scn.tex
> +                \scnfileitem{При оформлении sc.n-предложения осуществляется четкая \uline{табуляция} всех присоединенных к нему sc.n-предложений, присоединяемых к исходному по вертикали. Вертикальная
### 
```suggestion
                \scnfileitem{При оформлении sc.n-предложения осуществляется четкая \uline{табуляция} всех присоединенных к нему sc.n-предложений, присоединяемых к исходному по вертикали. Вертикальная линия табуляции задает левую границу исходного (максимального) sc.n-предложения или левую границу присоединенного sc.n-предложения, присоединяемого по вертикали. Левая граница sc.n-предложения задает начало первого sc-идентификатора, входящего в состав этого sc.n-предложения, а также начало sc.s-коннектора, инцидентного указанному sc-идентификатору и размещаемого \uline{строго под} этим sc-идентификатором. Расстояние между вертикальными табуляционными линиями фиксировано и примерно равно максимальной длине sc.s-коннектора.}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scn.tex
> +                \scnfileitem{В отличие от sc.s-текстов: в sc.n-текстах sc.s-коннектор может быть инцидентен предшествующему sc-идентификатору (как простому, так и sc-выражению) не только \scnqq{по го
```suggestion
                \scnfileitem{В отличие от sc.s-текстов: в sc.n-текстах sc.s-коннектор может быть инцидентен предшествующему sc-идентификатору (как простому, так и sc-выражению) не только \scnqq{по горизонтали}, но и по вертикали. Для этого sc.s-коннектор размещается строго \uline{под} предшествующим ему sc-идентификатором.}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scn.tex
> +                \scnfileitem{Кроме того \scnqq{по вертикали} sc-идентификатор может быть инцидентен не одному, а \uline{нескольким} sc.s-коннекторам, которые последовательно \scnqq{по вертикали} разм
```suggestion
                \scnfileitem{Кроме того \scnqq{по вертикали} sc-идентификатор может быть инцидентен не одному, а \uline{нескольким} sc.s-коннекторам, которые последовательно \scnqq{по вертикали} размещаются \uline{под} указанным sc-идентификатором. Это позволяет в рамках одного sc.n-предложения представлять произвольное число \scnqq{ответвлений} от каждого sc-идентификатора, т.е. произвольное число sc.s-коннекторов, инцидентных этому sc-идентификатору.}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scn.tex
> +                \scnfileitem{Каждый sc-идентификатор, включая sc-выражение, ограничиваемого фигурными или квадратными скобками, должен размещаться сразу правее вертикальной разметочной линии, если \u
```suggestion
                \scnfileitem{Каждый sc-идентификатор, включая sc-выражение, ограничиваемого фигурными или квадратными скобками, должен размещаться сразу правее вертикальной разметочной линии, если \uline{под ним} размещается sc.s-коннектор.}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scs.tex
> +            	\\При трансляции \textit{sc.s-текста} в \textit{SC-код} знаку равенства на некотором этапе может быть поставлено в соответствие \textit{sc-ребро}, принадлежащее отношению \textit{синоним
```suggestion
            	\\При трансляции \textit{sc.s-текста} в \textit{SC-код} знаку равенства на некотором этапе может быть поставлено в соответствие \textit{sc-ребро}, принадлежащее отношению \textit{синонимии}* \textit{sc-элементов}, идентифицируемых \textit{sc-идентификаторами}, связанными знаком равенства. Но на последующем этапе указанное \textit{sc-ребро} \uline{удаляется}, а связанные им \textit{sc-элементы} \uline{склеиваются}. Таким образом \textit{sc-ребро}, принадлежащее отношению \textit{синонимии}* sc-элементов, имеет не только денотационную, но и операционную семантику.}
            	\scnheader{знак равенства с включением}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scs.tex
> +            	\\Благодаря введению присоединенных sc.s-предложений появляется возможность любой sc-текст изобразить в виде одного sc.s-предложения, содержащего необходимое количество присоединенных sc
```suggestion
            	\\Благодаря введению присоединенных sc.s-предложений появляется возможность любой sc-текст изобразить в виде одного sc.s-предложения, содержащего необходимое количество присоединенных sc.s-предложений. Таким образом, SCs-код по выразительной мощности становится эквивалентным SCn-коду.}
            	\scnheader{sc.s-предложение}
```

2024-02-18 13:07 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_scs.tex
> +            	\\Указанные \textit{sc-идентификаторы}, \textit{sc.s-коннекторы} и \textit{sc.s-разделители}, изображающие связь инцидентности \textit{sc-элементов}, считаются компонентами соответствующ
```suggestion
            	\\Указанные \textit{sc-идентификаторы}, \textit{sc.s-коннекторы} и \textit{sc.s-разделители}, изображающие связь инцидентности \textit{sc-элементов}, считаются компонентами соответствующего \textit{sc.s-предложения}. Понятие быть компонентом sc.s-предложения\ является относительным понятием (отношением), т.к. в состав некоторых компонентов \textit{sc.s-предложения} (в состав \textit{sc-идентификаторов}, являющихся \textit{sc.s-выражениями}, ограничиваемыми фигурными или квадратными скобками) могут входить других \textit{sc.s-предложения}, состоящие из своих компонентов.}
            	\scnrelfrom{первый домен}{sc.s-предложение}
```

2024-02-18 20:06 UTC, NikitaZotov commented on Contents/part_kb/src/intro_lang/intro_latex_lang.tex
> +	\scnfileitem{входная конструкция}
Разве так работает?

2024-02-18 21:02 UTC, MksmOrlov requested changes

2024-02-18 21:02 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_scg.tex
> +                \end{scnrelfromset}
везде.либо list, если больше одного источника

2024-02-19 07:02 UTC, MksmOrlov requested changes
+ нерезолвнутые смотри

2024-02-19 07:02 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_scg.tex
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/7efd097e-db73-4b18-a5c6-4d48ed76674f)

2024-02-19 07:17 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_latex_lang.tex
> +	\scnfileitem{входная конструкция}
картинкой

2024-02-19 09:34 UTC, MksmOrlov approved these changes

2024-02-25 08:21 UTC, NikitaZotov approved these changes

2024-02-25 09:58 UTC, merged