part 1.3 integrated life cycle support technologies
ostis-ai/ostis-standard pull request #393
Opened 2024-02-21 11:01 UTC by PetrochukKsenija

2024-02-21 14:25 UTC, MakarenkoAI requested changes

2024-02-21 14:25 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +        \scntext{детализация}{\nameref{sd_ostis_ecosystem}}
Тут нужно вставлять текстом, если не отображается название. Везде нужно поменять.

2024-02-21 14:25 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scnheader{Cоздания технологии комплексного проектирования и комплексной поддержки последующих этапов жизненного цикла интеллектуальных компьютерных систем нового поколения}
```suggestion
    \scnheader{Cоздание технологии комплексного проектирования и комплексной поддержки последующих этапов жизненного цикла интеллектуальных компьютерных систем нового поколения}
```

2024-02-21 14:25 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +        Предложенную нами технологию комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового поколения мы назвали Технологией OSTIS (Open Semantic Technology for Intelligen
```suggestion
        \\Предложенную нами технологию комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового поколения мы назвали Технологией OSTIS (Open Semantic Technology for Intelligent Systems). Соответственно этому интеллектуальные компьютерные системы нового поколения, разрабатываемые по этой технологии называются ostis-системами. Сама Технология OSTIS реализуется нами в форме специальной ostis-системы, которая названа нами Метасистемой OSTIS}
```

2024-02-22 06:32 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scniselement{предметная область}
это не предметная область

2024-02-22 06:41 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +                \end{scnindent}
ссылки так не отображаются. Надо текстом полностью писать

2024-02-22 06:41 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \begin{scnindent}
лишний отступ

2024-02-22 06:45 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +        Предложенную нами технологию комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового поколения мы назвали Технологией OSTIS (Open Semantic Technology for Intelligen
этапы описываются не здесь. Этот текст относится ко множеству, которое представляет собой предъявляемые требования к технологии (выше)

2024-02-22 06:46 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +        \scnitem{Формальную теорию \textit{ostis-систем}}
```suggestion
        \scnitem{Формальная теорию \textit{ostis-систем}}
```

2024-02-23 11:00 UTC, MakarenkoAI requested changes

2024-02-23 11:00 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +        \scnitem{Формальная теорию \textit{ostis-систем}}
```suggestion
        \scnitem{Формальная теория \textit{ostis-систем}}
```

2024-02-23 16:37 UTC, MakarenkoAI approved these changes

2024-02-23 16:37 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scnheader{Создание инфраструктуры, обеспечивающей интенсивное перманентное развитие \textit{Технологии} \textit{комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового
```suggestion
    \scnheader{инфраструктура, обеспечивающая интенсивное перманентное развитие \textit{Технологии} \textit{комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового поколения}}
```
точно именно создание?

2024-02-23 16:37 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \end{scnindent}
```suggestion

     \scntext{детализация}{Логико-семантическая модель Метасистемы OSTIS}
  
```

2024-02-23 16:37 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \end{scnindent}
```suggestion

     \scntext{детализация}{Предметная область и онтология Экосистемы OSTIS}

```

2024-02-23 16:37 UTC, MakarenkoAI commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scntext{примечание}{Эффективная эксплуатация интероперабельных интеллектуальных компьютерных систем требует создания не только технологии проектирования таких систем, но также и семейства технол
```suggestion
    \scntext{заключение}{Эффективная эксплуатация интероперабельных интеллектуальных компьютерных систем требует создания не только технологии проектирования таких систем, но также и семейства технологий автоматизации всех остальных этапов их жизненного цикла. Особенно это касается технологии перманентной поддержки семантической совместимости всех взаимодействующих интероперабельных интеллектуальных компьютерных систем, а также технологии перманентной эволюции (модернизации) этих систем в ходе их эксплуатации.}
```

2024-02-23 17:57 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scntext{примечание}{Реализация всех перечисленных этапов развития технологий Искусственного интеллекта представляет собой переход на принципиально новый технологический уклад, обеспечивающий сущ
отступ нужен, чтобы отношение шло от этапов, а не от понятия "Технология комплексного проектирования и комплексной поддержки последующих этапов жизненного цикла интеллектуальных компьютерных систем нового поколения"

2024-02-23 17:57 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scnheader{Создание инфраструктуры, обеспечивающей интенсивное перманентное развитие \textit{Технологии} \textit{комплексной поддержки жизненного цикла интеллектуальных компьютерных систем нового
согласен с замечанием

2024-02-23 18:00 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \end{scnindent}
было правильно

2024-02-23 19:14 UTC, MksmOrlov requested changes

2024-02-23 19:14 UTC, MksmOrlov commented on Contents/part_intro/src/sd_ostis_tech.tex
> +    \scnheader{Комплексная технология поддержки жизненного цикла интеллектуальных компьютерных систем нового поколения}
Предметная область и онтология остаётся

2024-02-23 19:18 UTC, MksmOrlov approved these changes

2024-02-25 19:58 UTC, merged