fix: part 2.2
ostis-ai/ostis-standard pull request #395
Opened 2024-02-25 13:57 UTC by MakarenkoAI

2024-02-27 06:16 UTC, MksmOrlov requested changes
не могу найти это . Ты переводила только 2.2.1?
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/214c0e10-dfd1-4145-8963-d66c57e2ba13)

2024-02-27 06:41 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +                        \scnitem{обозначение связки}
и sc-множества?

2024-03-02 16:14 UTC, MksmOrlov requested changes

2024-03-03 20:20 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_8.tex
> +    \scnfileitem{Важнейшим достоинством \textbf{\textit{SC-пространства}} является возможность уточнения таких понятий, как понятие аналогичности (сходства и отличия) различных описываемых "внешних"{
Да, кавычки исправлю

2024-03-03 20:20 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_8.tex
> +	\scnheader{позже\scnrolesign}
Тут многие отношения есть в ПрО с логикой, из лучше убрать наверное

2024-03-03 20:20 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_8.tex
> +\scntext{примечание}{Вопросы соотнесения смыслов, их формализации, развития языков в пространстве и времени рассмотрены в работах В.В. Мартынова (см. \scncite{Martynov2004}, \scncite{Martynov2009}, \
и scncite перепроверю

2024-03-09 08:09 UTC, MksmOrlov requested changes

2024-03-09 08:09 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_8.tex
> +	\scnfileitem{Понятие \textbf{\textit{SC-пространства}} наряду с понятием \textbf{\textit{SC-кода}} является необходимым для уточнения и формализации понятия смысла \textit{информационных конструкций
это примечание дублируется с примечанием в конце первого сегмента. Надо оставить только в одном месте

2024-03-10 11:16 UTC, MksmOrlov approved these changes

2024-03-10 11:16 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +        \begin{scnrelfromvector}{быть заданным}
просто "задаётся"

2024-03-10 12:24 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +        \begin{scnrelfromvector}{быть заданным}
мне не нравится, если еще кто-то будет согласен с тобой и скажет поменять, то окей

2024-03-11 07:54 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_8.tex
> +	\scnheader{позже\scnrolesign}
не убирай, пусть будет как есть

2024-03-11 07:56 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +        \begin{scnrelfromvector}{быть заданным}
@ShunkevichDV, we need your opinion

2024-03-20 10:29 UTC, ShunkevichDV commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +            \scnfileitem{бинарное ориентированное отношением, определяющее непосредственный порядок (последовательность) символов в строках символов}
```suggestion
            \scnfileitem{бинарное ориентированное отношение, определяющее непосредственный порядок (последовательность) символов в строках символов}
```

2024-03-20 10:33 UTC, ShunkevichDV commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_2.tex
> +        \begin{scnrelfromvector}{быть заданным}
Затрудняюсь придумать хороший вариант, может быть хотя бы в инфинитиве написать типа "задаваться*". Обычно мы так делаем, если приходится использовать глагол, например "лежать между*". Лучше всего существительное, но я не могу его придумать, "задаваемость*" вроде нет такого слова

2024-04-22 19:59 UTC, merged