Part 5.2
ostis-ai/ostis-standard pull request #396
Opened 2024-03-08 18:51 UTC by SHtress

2024-03-10 10:05 UTC, MksmOrlov requested changes
Не нашёл введение, аннотацию, эпиграф и параграф 5.2.1 и 5.2.3 и 5.2.6 и заключение

2024-03-10 13:52 UTC, MakarenkoAI requested changes

2024-03-10 13:52 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +\scnnote{\textit{Реализация транслятора файлов исходных текстов базы знаний в sc-память ostis-платформы} позволяет осуществить сборку \textit{базы знаний} из набора файлов исходных текстов, записанны
```suggestion
\scnnote{\textit{Реализация транслятора файлов исходных текстов базы знаний в sc-память ostis-платформы} позволяет осуществить сборку \textit{базы знаний} из набора файлов исходных текстов, записанных в SCs-коде с ограничениями в бинарный формат, воспринимаемый \textit{Программной моделью sc-памяти}).
```
Такие ссылки не отображаются в документе, нужно искать названия ПрО (и т.д.) и прямо текстом вставлять через отношение \begin{scnrelfromset}{смотрите} ...

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools.tex
> +    ]{Предметная область и онтология ostis-системы редактирования, сборки и ввода исходных текстов различных компонентов проектируемой базы знаний в память ostis-системы}
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +	\scnitem{Режим создания sc.g-дуг}.
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +Для создания файлов исходных текстов в \textit{SCg-коде} может быть использован редактор \textbf{\textit{KBE}} (Knowledge Base source Editor, см. \scncite{Knowledge-base-editor2022}).}
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +\scnheader{Knowledge Base source Editor}
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/sd_detec_error.tex
> +	\item использовать унифицированный и удобный формат представления знаний;
Исправлено

2024-03-27 19:50 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +\scnnote{\textit{Реализация транслятора файлов исходных текстов базы знаний в sc-память ostis-платформы} позволяет осуществить сборку \textit{базы знаний} из набора файлов исходных текстов, записанны
Исправлено

2024-03-29 18:18 UTC, MksmOrlov requested changes

2024-03-29 18:18 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +	\scntext{аннотация}{В главе рассматриваются актуальные проблемы текущего состояния средств проектирования и анализа качества \textit{баз знаний}, предложен подход к их решению на основе \textit{Техн
```suggestion
	\scntext{аннотация}{В предметной области и онтологии рассматриваются актуальные проблемы текущего состояния средств проектирования и анализа качества \textit{баз знаний}, предложен подход к их решению на основе \textit{Технологии OSTIS}. Сформулированы принципы коллективного проектирования и разработки \textit{баз знаний}. Сформулированы принципы верификации \textit{баз знаний}.}
```

2024-03-30 06:59 UTC, SHtress commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +	\scntext{аннотация}{В главе рассматриваются актуальные проблемы текущего состояния средств проектирования и анализа качества \textit{баз знаний}, предложен подход к их решению на основе \textit{Техн
Исправлено

2024-03-30 12:10 UTC, MksmOrlov requested changes
Не нахожу 5.2.1

2024-03-31 08:29 UTC, SHtress commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +		\end{scnrelfromlist}
Исправлено

2024-04-01 15:00 UTC, MksmOrlov requested changes

2024-04-01 15:00 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +			}
надо формализовать

2024-04-01 15:00 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +		%%%%%%%%%%%%%%%%%%%%%%%
зачем такие комментарии?

2024-04-02 13:07 UTC, SHtress commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +			}
Исправлено

2024-04-02 13:07 UTC, SHtress commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +		%%%%%%%%%%%%%%%%%%%%%%%
Нужны были для визуального отделения при  переносе материала. 
Убрано

2024-04-22 19:27 UTC, MksmOrlov requested changes

2024-04-22 19:27 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +				\scntext{пояснение}{Индивидуальный представляет собой наполнение изолировнной части \textit{базы знаний} конкретным пользователем}
включение в другую сторону, значок \scnsuperset, без знака множества, сразу к аспектам

2024-04-22 19:27 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +		\scnheader{vетодология разработки онтологий}
```suggestion
		\scnheader{методология разработки онтологий} 
```

2024-04-22 19:27 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +		\scnheader{Стартовая версия \textit{ostis-системы}}
```suggestion
		\scnheader{стартовая версия \textit{ostis-системы}}
```
думаю, это класс

2024-04-22 19:27 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +				\begin{scnreltovector}{включение}
я бы сделал отношение "этапы" и в другую сторону дуга

2024-04-22 19:27 UTC, MksmOrlov commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +\scnheader{команды меню KBE}
эта и следующие сущности должны быть связаны каким-то отношением с KBE, иначе несвязно получается

2024-04-25 18:57 UTC, SHtress commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +				\scntext{пояснение}{Индивидуальный представляет собой наполнение изолировнной части \textit{базы знаний} конкретным пользователем}
Уточни  "значок \scnsuperset, без знака множества, сразу к аспектам" более детально, не понимаю что ожидается

2024-04-25 18:57 UTC, SHtress commented on Contents/part_methods_tools/src/edit_assem_logical_model.tex
> +\scnheader{команды меню KBE}
Подумаю над этим

2024-04-26 09:51 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +				\scntext{пояснение}{Индивидуальный представляет собой наполнение изолировнной части \textit{базы знаний} конкретным пользователем}
Сверху как было, снизу как хочу. 

![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/2469325a-7a3b-457d-a299-263a27b37354)
Я думаю, так будет правильнее. Когда ты делаешь включение и описываешь явно множество, то это то же самое, что вписать две принадлежности. А принадлежности тут по смыслу не подходят, как я это понимаю

2024-04-27 09:09 UTC, MksmOrlov requested changes
fix unresolved please

2024-04-28 05:25 UTC, SHtress commented
Please, resolve fixed problems or add comments why you think problem is not fixed after changes 🙂

2024-04-28 15:22 UTC, MksmOrlov requested changes

2024-04-28 15:22 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +				\begin{scnreltovector}{этапы}
```suggestion
				\begin{scnrelfromvector}{этапы}
```

2024-05-04 17:51 UTC, MksmOrlov requested changes
Перенеси пожалуйста этот комментарий в part_method_toolstex в место, где label стоит одноименный. Из-за этого не собирается нужный scs код при трансляции. А сам файл edit_tools_proj_logical_model.tex удали пожалуйста
![image](https://github.com/ostis-ai/ostis-standard/assets/36566977/4945f45d-9b93-47e1-81b1-db60c28ce12e)

2024-05-12 13:56 UTC, MksmOrlov requested changes

2024-05-12 13:56 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +        \begin{scnindent}
этот \begin{scnindent} вместе с \end{scnindent} лишние. Из-за этого также база не собирается

2024-05-17 06:36 UTC, MksmOrlov approved these changes

2024-05-21 15:35 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_author.tex
> +	\scnidtf{бинарное отношение, связывающее sc-элемент, обозначающий некоторый раздел базы знаний (в пределе --- всю базы знаний), и sc-элемент, обозначающий пользователя ostis-системы, который может б
```suggestion
	\scnidtf{бинарное отношение, связывающее sc-элемент, обозначающий некоторый раздел базы знаний (в пределе --- всю базу знаний), и sc-элемент, обозначающий пользователя ostis-системы, который может быть разработчиком данного раздела базы знаний, то есть выполнять проектные задачи в рамках данного раздела}
```

2024-05-21 15:42 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +        \end{scnindent}
Выше дублирует. Предлагаю удалить, начиная с 29 строки, а эту часть оставить

2024-05-21 15:44 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +        \scnheader{многократно используемый компонент баз знаний ostis-систем}
еще есть Многогратно используемый компонент баз знаний и базЫ знаний, тут что-то нехорошее

2024-05-21 15:49 UTC, MakarenkoAI commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +        \scnhaselement{максимальный класс объектов исследования'}
```suggestion
        \scnhaselement{максимальный класс объектов исследования\scnrolesign}
```
 везде поменять можно

2024-05-29 10:38 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_actions_methodology_know_base_design.tex
> +		\scnnote{Данная методика предполагает два основных этапа --- этап создания стартовой версии разрабатываемой \textit{ostis-системы}, \textit{база знаний} которой синтезируется из \textit{компонентов
нужны

2024-05-29 10:40 UTC, MksmOrlov commented on Contents/part_methods_tools/src/sd_know_base_component.tex
> +        \scnheader{многократно используемый компонент баз знаний ostis-систем}
Надо **базы знаний**. Используем тот идентификатор, который определён в главе 5.1 про библиотеку

2024-08-01 15:38 UTC, closed without merging