feat: add sd_logic and sd_product
ostis-ai/ostis-standard pull request #407
Opened 2024-05-23 17:09 UTC by kilativ-dotcom

2024-05-31 18:18 UTC, ShunkevichDV requested changes

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +    \scnitem{близкость к логическим моделям}
Все неформализованные вещи я бы делал файлами, вряд ли у нас будет явно выделенная сущность под названием "близкость к логическим моделям" или "наглядность отображения знаний логических моделей"

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +    \scnrelto{простота интеграции}{решатель задач ostis-системы}
С новыми отношениями тоже лучше быть осторожнее, если пока не ясно, как что-то формализовать, то лучше оставить примечанием или комментарием. В данном случае какие домены у этого отношения? Какова его семантика, что с чем интегрируется?

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +        \scnrelfrom{составная часть}{объект}
объект и атрибут - очень плохие понятия, они могут иметь десятки разных смыслов в разных контекстах. Рабочая память думаю тоже. Лучше оставлять неформализованными какие-то фрагменты текста, чем просто вот так пытаться нарезать их на термины

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +        \scnrelfrom{составная часть}{явные данные структуры управления}
Есть отношение "часть*" и "обобщенная часть*", но в данном контексте все равно не понятно, что является вторым компонентом

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +            \scnrelfrom{элемент множества}{элемент конфликтного множества}
Ну элемент множества это уж совсем печальное отношение, для этого есть отношение принадлежности у нас, которое выражается базовыми дугами.
Но не думаю, что здесь оно подходит, интерпретатор это в лучше случае множество агентов, тут явно не то

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +    \scnrelfrom{продукция}{продукция OPS5}
Перепутаны классы и экземпляры. Речь явно идет про продукцию языка OPS5 в целом как класс, а перечисляются компоненты с ролями, как если бы описывали конкретную продукцию.

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +\begin{scnrelfromlist}{составной элемент}
- лучше использовать известные отношения, такие как часть, декомпозиция и т.д.
- снова подменяются понятия, язык CLIPS не содержит базу фактов CLIPS, конкретная программа данного языка может ее содержать. 
- англоязычный идентификатор явно шире русскоязычного

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_oper_sem.tex
> +\scnnote{Содержит обобщение логики функционала, ответственного за связь данных (фактов) и алгоритма (продукций) в системах сопоставления с образцом (вид систем: системы основанные на правилах). Проду
В этом файле формализация получше, но тем не менее, все пояснения и примечания нужно писать так, чтобы они воспринимались без контекста. Говоря другими словами, в них должна упоминаться сама описываемая сущность.

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_oper_sem.tex
> +\begin{scnrelfromset}{объединяемые области}
Перечислены вперемежку как классы конкретных объектов, так и области науки, с формальной точки зрения ничего не ясно. То, что авторы вероятно сами так пишут, не значит, что мы должны им уподобляться

2024-05-31 18:18 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +    \scnhaselement{i}
Снова путается класс и экземпляр, см. комментарий выше.

2024-06-18 21:17 UTC, shaversion commented on Contents/part_ps/src/images/sd_operat_sem_sc_logical_lang/Modus_ponens.png
Есть замечания и вопросы. Почему формула не замкнутая?
Разве так мы показываем выводимость?

2024-06-18 21:18 UTC, shaversion commented on Contents/part_ps/src/images/sd_operat_sem_sc_logical_lang/conjunction_implication_rule.png
Есть замечания и вопросы. Разве так мы показываем выводимость?

2024-06-18 21:19 UTC, shaversion commented on Contents/part_ps/src/images/sd_operat_sem_sc_logical_lang/direct_inference_agent.png
Почему постоянная принадлежность?

2024-06-18 21:20 UTC, shaversion commented on Contents/part_ps/src/images/sd_operat_sem_sc_logical_lang/resolution.png
Есть замечания и вопросы. Количество элементов в дизъюнкции? Разве так мы показываем выводимость?

2024-06-18 21:21 UTC, shaversion commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
*кость? есть такое слово?

2024-06-18 21:22 UTC, shaversion commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +    \scnitem{близкость к логическим моделям}
для кого наглядный?

2024-06-18 21:25 UTC, shaversion commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +    \scnrelto{простота интеграции}{решатель задач ostis-системы}
условие чего?
какие ограничения жёсткие?
объект интеграции где? не понятно

2024-06-18 21:27 UTC, shaversion commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +    \scnrelto{простота интеграции}{решатель задач ostis-системы}
что будет результатом объединения? сомнительная фраза

2024-06-18 21:29 UTC, shaversion commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +            \scnrelfrom{элемент множества}{элемент конфликтного множества}
В некоторых случаях оно может быть полезно, если надо указать конец элемент множества, обозначенного дугой.

2024-06-26 19:11 UTC, kilativ-dotcom commented on Contents/part_ps/src/images/sd_operat_sem_sc_logical_lang/Modus_ponens.png
так нарисовано у авторов, этот пул запрос просто переносит главу из монографии

2024-06-26 19:12 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +    \scnhaselement{i}
хотелось показать, что у формулы есть подстроки и расписать что они означают

2024-07-20 14:05 UTC, ShunkevichDV requested changes

2024-07-20 14:05 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +\begin{scnrelfromlist}{изображение}
А почему тут scnrelfromlist?
Достаточно просто scnrelfrom на мой взгляд, потом идентификатор рисунка, а потом еще один scnindent

2024-07-20 14:05 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_denot_sem.tex
> +\scnnote{\textbf{\textit{CLIPS}} использует продукционную модель представления знаний и поэтому содержит три основных элемента:
Хотя бы один раз за все описание надо бы использовать scnexplanation, иначе получается, что всё примечания, а пояснения и нет

2024-07-20 14:05 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +\begin{scnrelfromset}{декомпозиция}
обобщенная декомпозиция, мы хотим сказать, что **каждая** программа состоит из этих частей

2024-07-20 14:05 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +\begin{scnrelfromset}{декомпозиция}
Кроме того, мы точно уверены, что это работает вообще для всех-всех программ на продукционном языке?

2024-07-20 14:05 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +\scnheader{программа на продукционном языке программирования}
Если это действительно программа, то стоит сделать подмножеством понятия метод

2024-07-20 16:18 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +\scnnote{Продукции наряду с фреймами являются наиболее популярными средствами представления знаний в интеллектуальных компьютерных системах.}
я поискал где такой же текст используется и нашёл [статью](https://top-technologies.ru/ru/article/view?id=35973) у которой девять самоцитирований и одна ссылка на `Загоруйко Н.Г. Вычислительные системы. Экспертные системы и анализ данных: Сборник научных трудов. – Новосибирск, 1991. – 177 с.`, я подозреваю, что взято оттуда, так как год +- сходится, но не получилось найти электронную версию сборника
остальные совпадения этого текста слишком подозрительные, чтоб их источником считать, выглядят как копипасты откуда-то

2024-07-20 16:18 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +\begin{scnrelfromset}{декомпозиция}
в оригинале было
`
Продукционный язык программирования в общем случае может содержать структурные единицы различного характера. Это могут быть определения глобальных переменных, операторы управления макрогенерацией, вставки текстов на алгоритмических языках программирования и целый ряд других элементов. Однако основной единицей продукционного языка программирования, определяющей его лицо и его возможности, является продукция.
`
приписка с `и целый ряд других элементов` должна все программы покрывать, но в декомпозицию это же не переносится

2024-07-21 13:13 UTC, ShunkevichDV requested changes

2024-07-21 13:13 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\scniselement{система логического программирования}
Странно, что язык это одновременно система
Надо разделить эти понятия, например, Пролог и Система программирования Пролог

2024-07-21 13:13 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\scnnote{\textit{база знаний} системы \textit{Пролог} содержит информацию в виде предикатов. В логическом программировании, реализованном в \textit{Прологе}, используется только одно \textit{правило
Нужно определиться, система Пролог это класс систем или конкретная система. Я думаю все же класс, тогда надо уточнить, что база знаний каждой системы Пролог

2024-07-21 13:13 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\scnheader{теорема}
Я не знаю, где этот материал сейчас, но раньше в стандарте была ПрО логических формул, где теорема и аксиома были ролевыми отношениями, задающими роль формулы в рамках конкретной формальной теории. В разных теориях роли могут быть разные. Нужно согласовать

2024-07-21 13:13 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\begin{scnrelfromset}{декомпозиция}
А почему декомпозиция? Может это разновидность, тогда включение

2024-07-24 20:34 UTC, MksmOrlov requested changes

2024-07-24 20:34 UTC, MksmOrlov commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\scnrelto{пример использования}{Задача с футбольными командами}
в другую сторону дугу нужно

2024-07-24 20:34 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
это к чему?

2024-07-24 20:34 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_product_program_lang.tex
> +\end{scnrelfromlist}
надо написать м.к.о.и.

2024-07-24 20:34 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +    \scntext{подстрока}{($i$); $Q$; $P$; $A$ $\Rightarrow$ $B$; $N$}
не думаю, что надо эти подстроки формализовывать, я бы писал сразу текст примечания

2024-09-17 08:41 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\scniselement{предметная область}
добавил максимальный, насчёт остальных не уверен что хотели сказать авторы главы

2024-09-17 08:41 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +        \end{scnstruct}
это ты имеешь в виду title_part/src/toc.tex? там полотно предметных областей и онтологий, а тут просто предметные области

2024-09-17 08:42 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +    	\scnnote{Наследование предметных областей позволяет использовать описанные логики и их компоненты при описании любых логик. Базовые понятия позволяют разработчикам интеллектуальной системы добав
оно выглядит как примечание ко всей иерархии, + не понял куда эту иерархию перенести

2024-09-17 10:33 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_sc_product_program_lang_syntax.tex
> +    \scntext{подстрока}{($i$); $Q$; $P$; $A$ $\Rightarrow$ $B$; $N$}
удалил отсюда промежуточную подстроку

2024-09-17 10:35 UTC, kilativ-dotcom commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\end{scnhaselementrolelist}
не понял что имеешь в виду

2024-10-16 11:48 UTC, ShunkevichDV approved these changes

2024-10-16 11:48 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +        \end{scnstruct}
Нужно выработать правила общие, пока можно оставить я думаю

2024-10-16 11:48 UTC, ShunkevichDV commented on Contents/part_ps/src/sd_operat_sem_sc_logical_lang.tex
> +\end{scnhaselementrolelist}
Да вроде бы здесь...

2024-10-16 12:00 UTC, merged