[fix] Rename ims.ostis
ostis-ai/ostis-standard pull request #408
Opened 2024-06-11 10:24 UTC by MakarenkoAI

2024-06-11 10:58 UTC, MksmOrlov requested changes

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_beginning.tex
> +        \item спецификация библиографических источников (в контексте \textit{Базы знаний OSTIS});
```suggestion
        \item спецификация библиографических источников (в контексте \textit{Базы знаний Метасистемы OSTIS});
```

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment3.tex
> +            \item для разработчиков \textit{интеллектуальных компьютерных систем}, желающих использовать для этого \textit{Технологию OSTIS} (эти разработчики являются конечными пользователями \texti
```suggestion
            \item для разработчиков \textit{интеллектуальных компьютерных систем}, желающих использовать для этого \textit{Технологию OSTIS} (эти разработчики являются конечными пользователями \textit{Метасистемы OSTIS});
```

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment4.tex
> +	    \scntext{примечание}{При \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (точнее ostis-систем) средством автоматизации этой деятельности яв
```suggestion
	    \scntext{примечание}{При \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (точнее ostis-систем) средством автоматизации этой деятельности является не вся \textit{Метасистема OSTIS}, а только ее часть --- входящая в состав \textit{Метасистемы OSTIS} типовая \textit{Встраиваемая ostis-система поддержки реижиниринга ostis-систем}, которая поддерживает деятельность разработчиков базы знаний Метасистемы IMS.оstis. Это обусловлено тем, что вся деятельность по \textit{Разработке Базовой Комплексной технологии проектирования интеллектуальных компьютерных систем} (ostis-систем) сводится к разработке (инженирингу) и обновлению (совершенствованию, реинжинирингу) \textit{Базы знаний Метасистемы OSTIS}).}
```

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment4.tex
> +    \scnidtf{Человеко-машинная деятельность, осуществляемая в рамках \textit{Экосистемы OSTIS} и направленная на разработку и перманентное совершенствование \textit{Метасистемы OSTIS}, которая являет
```suggestion
    \scnidtf{Человеко-машинная деятельность, осуществляемая в рамках \textit{Экосистемы OSTIS} и направленная на разработку и перманентное совершенствование \textit{Метасистемы OSTIS}, которая является формой представления (отображения) (1) текущего состояния \textit{Технологии OSTIS}, как комплекса методов и средств автоматизации (поддержки) разработки\textit{ostis-систем} и (2) текущего состояния самого \textit{Проекта Метасистемы OSTIS}.}
```
Моё личное мнение, что надо везде заменить

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment5.tex
> +                    Нет центральных и периферийных публикаций --- есть общая база знаний, в которой нет семантической эквивалентности(и, следовательно, нет плагиата). Монография OSTIS \textbf{+ OSTIS
```suggestion
                    Нет центральных и периферийных публикаций --- есть общая база знаний, в которой нет семантической эквивалентности (и, следовательно, нет плагиата). Монография OSTIS + \textbf{Метасистема OSTIS} как новый уровень автоматизации создания и эволюции научно-технического каталога статей и монографий к семантически совместимым базам и порталам научно-технических знаний! Достоинства эволюции портала научных знаний по Искусственному интеллекту и соответственно сообщества ученых распространяется на все научные дисциплины}
```
Не уверен, что тут должно быть так, но сейчас явно ерунда какая-то

2024-06-11 10:58 UTC, MksmOrlov commented on Contents/part_intro/src/sd_sem_inf_rep.tex
> +				\scnhaselement{раздел Базы знаний OSTIS}
```suggestion
				\scnhaselement{раздел Базы знаний Метасистемы OSTIS}
```

2024-06-11 10:58 UTC, MksmOrlov commented on README.md
> +Репозиторий содержит исходные файлы документации Технологии OSTIS, оформленной в виде исходного текста [базы знаний Метасистемы OSTIS](https://github.com/ostis-ai/ims.ostis.kb). База знаний представл
```suggestion
Репозиторий содержит исходные файлы документации Технологии OSTIS, оформленной в виде исходного текста Базы знаний Метасистемы OSTIS. База знаний представляет собой иерархическую систему связанных между собой формальных моделей предметных областей и соответствующих
```

2024-06-11 14:46 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment3.tex
> +    \scntext{примечание}{Форма реализации \textit{Ядра Технологии OSTIS} (в виде ostis-системы \textit{Метасистемы OSTIS}) позволяет:
(в виде \textit{Метасистемы OSTIS})

2024-06-11 14:46 UTC, MksmOrlov commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment5.tex
> +                    Нет центральных и периферийных публикаций --- есть общая база знаний, в которой нет семантической эквивалентности(и, следовательно, нет плагиата). Монография OSTIS \textbf{+ OSTIS
здесь нужен @ShunkevichDV

2024-06-18 09:05 UTC, ShunkevichDV approved these changes
С учетом комментария от Максима

2024-06-18 09:06 UTC, ShunkevichDV commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment3.tex
> +    \scntext{примечание}{Форма реализации \textit{Ядра Технологии OSTIS} (в виде ostis-системы \textit{Метасистемы OSTIS}) позволяет:
Согласен

2024-06-18 09:07 UTC, ShunkevichDV commented on Contents/part_ecosystem/src/intro_ostis/intro_ostis_segment5.tex
> +                    Нет центральных и периферийных публикаций --- есть общая база знаний, в которой нет семантической эквивалентности(и, следовательно, нет плагиата). Монография OSTIS \textbf{+ OSTIS
Согласен с предложением Максима

2024-07-12 11:35 UTC, MksmOrlov approved these changes

2024-08-01 15:30 UTC, merged