3.6
ostis-ai/ostis-standard pull request #409
Opened 2024-06-21 13:58 UTC by MakarenkoAI

2024-06-28 09:01 UTC, PetrochukKsenija requested changes

2024-06-28 09:01 UTC, PetrochukKsenija commented on Contents/part_ps/src/ann/sd_oper_sem.tex
> +		\begin{scnitemize}
поправить список в тексте

2024-06-28 10:31 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ann.tex
> +		\begin{scnitemize}
Я не понимаю этой семантической разницы, но что-то исправила

2024-07-01 10:17 UTC, MksmOrlov requested changes

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/sd_ann.tex
> +            S = \sum_{i=1}^{n} w_ix_i - T
надо тест ниже сделать примечанием к формуле. A то получилась огромная сущность нелогичная

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/sd_ann.tex
> +            S = \sum_{i=1}^{n} w_ix_i - T
Во всех формулах остальных тоже

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/ann/sd_denot_sem.tex
> +\end{scnindent}
Думаю, отступ тут лишний. Вместо отношения "изображение" сразу делай "пример*"

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/ann/sd_denot_sem.tex
> +\end{scnindent}
Отступ лишний. Из-за этого, кроме прочего, трансляция ломается

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/sd_ann.tex
> +    \scnrelto{включение}{метод}
везде

2024-07-01 10:17 UTC, MksmOrlov commented on Contents/part_ps/src/ann/sd_oper_sem.tex
> +		\scnitem{метод обучения и.н.с.}
думаю, алгоритм обучения и метод обучения одно и то же. Надо чтобы в разбиении получилось два элемента - с учителем и без

2024-07-02 08:29 UTC, MksmOrlov commented on Contents/part_ps/src/ann/sd_oper_sem.tex
> +\scnheader{Таблица. Результаты решения задачи}
а ещё мы таблицу в scs не протранслируем

2024-07-02 09:11 UTC, MksmOrlov requested changes
есть неисправленное

2024-07-04 08:47 UTC, PetrochukKsenija commented on Contents/part_ps/src/ann/sd_oper_sem.tex
> +\scntext{определение}{\textit{функция потерь} --- функция, используемая для вычисления ошибки, рассчитываемой как разница между фактическим эталонным значением и прогнозируемым значением, получаемым
тут моя ошибка. надо вернуть, как было. Даниил Вячеславович сказал, что в таком случае нужно дублировать сам термин

2024-07-04 09:16 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ann.tex
> +	\scnfileitem{Перспективными и активно развивающимися методами решения задач являются искусственные нейронные сети	(и.н.с.), что обуславливается, с одной стороны, развитием теории и.н.с., а с другой
```suggestion
	\scnfileitem{Перспективными и активно развивающимися методами решения задач являются искусственные нейронные сети (и.н.с.), что обуславливается, с одной стороны, развитием теории и.н.с., а с другой --- аппаратных возможностей машин, которые используются для их обучения.}
```

2024-07-04 09:16 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ann.tex
> +	\scnfileitem{Современные решатели задач интеллектуальных систем все чаще сталкиваются с необходимостью решения комплексных задач с помощью различных традиционных и интеллектуальных методов решения з
```suggestion
	\scnfileitem{Современные решатели задач интеллектуальных систем все чаще сталкиваются с необходимостью решения комплексных задач с помощью различных традиционных и интеллектуальных методов решения задач в едином информационном ресурсе (в пределе --- в единой базе знаний).}
```

2024-07-04 09:16 UTC, PetrochukKsenija commented on Contents/part_ps/src/ann/sd_denot_sem.tex
> +		\scntext{пояснение}{ Отдельный обрабатывающий элемент и.н.с., выполняющий функциональное преобразование взвешенной суммы элементов вектора входных значений с помощью функции активации.}
```suggestion
		\scntext{пояснение}{Отдельный обрабатывающий элемент и.н.с., выполняющий функциональное преобразование взвешенной суммы элементов вектора входных значений с помощью функции активации.}
```

2024-07-04 09:16 UTC, PetrochukKsenija commented on Contents/part_ps/src/ann/sd_oper_sem.tex
> +		\begin{scnitemize}
везде, где используются scnitemize для создания списков в блоке текста (текстовой ссылке), необходимо заменить на itemize
Никита сказал, что scn-tex не может использоваться в простых блоках текста

2024-07-05 15:14 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ann.tex
> +	\scnitem{Язык представления нейросетевых методов решения задач в базах знаний}
исправлю через 1 коммит, когда точно узнаю

2024-07-05 16:35 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ann.tex
> +	\scnitem{Язык представления нейросетевых методов решения задач в базах знаний}
через ключевой знак

2024-07-17 08:32 UTC, merged