feat(kb) Move part 2.1 to standard
ostis-ai/ostis-standard pull request #410
Opened 2024-06-22 14:47 UTC by MakarenkoAI

2024-06-27 18:04 UTC, MksmOrlov requested changes

2024-06-28 09:46 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang.tex
> +        \scntext{определение}{Дискретные информационные конструкции $\bm{Ti}$ и $\bm{Tj}$ являются синтаксически эквивалентными в том и только в том случае, если между конструкцией $\bm{Ti}$ и констр
Зачем, не понимаю, но ладно

2024-06-28 10:11 UTC, MakarenkoAI commented on Contents/part_kb/src/intro_lang.tex
> +        	\scntext{определение}{бинарное отношение, связывающее язык и синтаксически правильную (правильно построенную) знаковую конструкцию данного языка.}
Пересмотри, пожалуйста. Не нашла

2024-06-28 15:38 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang.tex
> +        \scntext{определение}{Дискретные информационные конструкции $\bm{Ti}$ и $\bm{Tj}$ являются синтаксически эквивалентными в том и только в том случае, если между конструкцией $\bm{Ti}$ и констр
Потому что так более понятно и более официально написано. В монографии так же было

2024-06-28 15:40 UTC, MksmOrlov approved these changes

2024-06-29 06:30 UTC, PetrochukKsenija requested changes

2024-06-29 06:30 UTC, PetrochukKsenija commented on Contents/part_kb/src/intro_lang.tex
> +            \scnidtf{Множество ориентированных пар, первым компонентом которых является ориентированная пара, состоящая из (1) знака синтаксической структуры некоторой информационной конструкции и (2
это определение должно относиться к понятию "соответствие, заданное на множестве дискретных информационных конструкций", а сейчас оно относится к понятию "соответствие между синтаксической структурой информационной конструкции и смыслом этой конструкции*"

2024-07-12 11:31 UTC, MksmOrlov approved these changes

2024-07-17 08:18 UTC, merged