feat(kb) Move 2.7 part to standard
ostis-ai/ostis-standard pull request #411
Opened 2024-06-23 12:02 UTC by MakarenkoAI

2024-07-01 11:55 UTC, MksmOrlov requested changes

2024-07-01 11:55 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \begin{scnrelfromlist}{ключевое знание}
переделать в классы объектов исследования и тп

2024-07-01 11:55 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scntext{примечание}{Пример формализации \textit{отношений} в \textit{SCg-коде}.}
сделай "пример*" от понятия лексемы к этому рисунку. База знаний должна быть связной здесь. Примечание можно убрать

2024-07-01 11:55 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scntext{примечание}{Пример формализации \textit{отношений} в \textit{SCg-коде}.}
Проверь везде

2024-07-04 07:51 UTC, PetrochukKsenija requested changes

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \scntext{пояснение}{\textit{Комбинторный вариант лексемы} --- вариант лексемы в упорядоченном наборе её вариантов (парадигме).}
```suggestion
        \scntext{определение}{вариант лексемы в упорядоченном наборе её вариантов (парадигме)}
```

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_natural_languages.tex
Пояснение в номинативной единице лучше оформить как определение, а пример вынести отдельным отношением для этого понятия

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +                \scntext{пояснение}{\textit{Именная группа} --- \textit{синтаксическая группа}, \textit{вершиной} которой является \textit{существительное}.}
```suggestion
                \scntext{определение}{\textit{Именная группа} --- \textit{синтаксическая группа}, \textit{вершиной} которой является \textit{существительное}.}
```
Тут всё лучше во всех элементах множества заменить пояснение* на определение*

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \begin{scnrelfromvector}{пример}
в этом примере лучше возможные структуры синтаксических групп связать с конктретными группами, которые описывались выше, чтобы потом при поиске в метасистеме при отображении конкретной группы отображалась и возможная структра конктретной группы

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scntext{примечание}{Правила структуры синтаксических групп можно обобщить и свести к трем более абстрактным.
каждое правило должно быть отдельной сущностью с пояснением и связано с теми, что есть ниже, где идет привязка к изображению

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        \scntext{пояснение}{Мы предлагаем вариант формализации \textit{денотационной семантики} \textit{естественных языков} в рамках \textit{Технологии OSTIS}, для составления которой использовались
```suggestion
        \scntext{пояснение}{Предлагается вариант формализации \textit{денотационной семантики} \textit{естественных языков} в рамках \textit{Технологии OSTIS}, для составления которой использовались стандартные положения формальной семантики.}
```

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        \scntext{примечание}{\textit{денотационная семантика} \textit{языка} специфицирует интерпретацию элементов \textit{синтаксиса} данного \textit{языка} и представляет собой множество формул, оп
```suggestion
        \scntext{примечание}{\textit{Денотационная семантика} \textit{языка} специфицирует интерпретацию элементов \textit{синтаксиса} данного \textit{языка} и представляет собой множество формул, описывающих то, каким образом \textit{информационным конструкциям} \textit{языка} ставятся в соответствие обозначаемые ими сущности и конфигурации отношений между этими сущностями.}
```

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        \scntext{примечание}{\textit{денотационная семантика} \textit{естественных языков} должна обладать свойством композициональности --- то есть интерпретация всего высказывания должна выводиться
```suggestion
        \scntext{примечание}{\textit{Денотационная семантика} \textit{естественных языков} должна обладать свойством композициональности --- то есть интерпретация всего высказывания должна выводиться из интерпретации отдельных его частей.
```

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        \scnheader{правила, реализующие \textit{денотационную семантику} \textit{языка}}
Нужно пресмотреть этот блок с правилами. Выделить все правила как отдельные элементы и дать пояснение правилу. Также связать каждое правило с соответсвующей ему картиинкой

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +            \scnfileitem{Смыслом таких конструкций является класс, являющийся результатом \textit{пересечения} классов, полученных в результате интерпретации \textit{вершин} \textit{групп прилагатель
это не отдельный блок, а пояснение к правилу выше

2024-07-04 07:51 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        \scnheader{правила, реализующие \textit{денотационную семантику} \textit{языка}}
тут ещё не хватает одного правила (Правило интерпретации максимальной проекции вершины временной группы). Оно почему-то описано под картинкой. Надо это исправить

2024-07-04 08:09 UTC, PetrochukKsenija commented on Contents/part_kb/src/sd_natural_languages.tex
> +            \begin{scnitemize}
Никита сказал, что в трансляторе внутри текстовых ссылок используется просто itemize, поэтому это надо везде исправить

2024-07-05 15:27 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_natural_languages.tex
> +            \scnfileitem{\textit{онтологии} \textit{естественного языка} активно применяются для генерации текстов \textit{естественного языка} на основе некоторой \textit{онтологии} предметной облас
Там источники разные вроде, не получится

2024-07-05 15:28 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \begin{scnrelfromvector}{введение}
Из-за ссылок на источники разбито по предложениям

2024-07-05 15:33 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \begin{scnrelfromvector}{пример}
каким отношением?

2024-07-05 15:48 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scntext{примечание}{Правила структуры синтаксических групп можно обобщить и свести к трем более абстрактным.
Максим разрешил не формализовывать этот текст

2024-07-11 13:09 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
>              \scnitem{Базовые правила денотационной семантики естественных языков}
это все-таки не классы, надо другое отношение использовать. Глянь в предметной области предметных областей как точно называется подходящее отношение

2024-07-11 13:09 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +            \scnfileitem{\textit{онтологии} \textit{естественного языка} активно применяются для генерации текстов \textit{естественного языка} на основе некоторой \textit{онтологии} предметной облас
ничего страшного, будет у одной ссылки несколько источников

2024-07-11 13:09 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \begin{scnrelfromvector}{введение}
ничего страшного, будет у одной ссылки несколько источников

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +                    \end{scnindent}
Эта конструкция не связывает 4 страницу с ЕЯ-фрагментом, здесь как будто просто сказано, что у источника есть 4 страница, а не что текст связана с тем, что на 4 странице есть. Надо по-другому формализовывать.

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +                    \end{scnindent}
Проверь в других местах этого ПРа

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +                \begin{scnrelfromset}{источник}
```suggestion
                \begin{scnrelfromset}{смотрите}
```

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +    \bigskip
зочем

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \scnrelfrom{пример}{SCg-текст. Иллюстрация к спецификации лексемы в базе знаний}
я бы сразу здесь и вставил пример, не разрывать их

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \scntext{определение}{\textit{Номинативная единица} --- устойчивая последовательность комбинторных вариантов лексем, в которой один вариант лексемы (модификатор) определяет другой (актуализат
```suggestion
        \scntext{определение}{\textit{номинативная единица} --- устойчивая последовательность комбинторных вариантов лексем, в которой один вариант лексемы (модификатор) определяет другой (актуализатор), например: записная книжка, бежать галопом.}
```

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
> +        \scntext{определение}{\textit{Номинативная единица} --- устойчивая последовательность комбинторных вариантов лексем, в которой один вариант лексемы (модификатор) определяет другой (актуализат
проверь везде

2024-07-11 15:48 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \begin{scnrelfromvector}{пример}
включение видимо

2024-07-12 11:16 UTC, MksmOrlov commented on Contents/part_kb/src/sd_natural_languages.tex
>              \scnitem{Базовые правила денотационной семантики естественных языков}
![image](https://github.com/user-attachments/assets/43d82407-f8d4-4386-ac14-a242b3b6c5e1)

2024-07-15 09:54 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_natural_languages.tex
> +            \scnfileitem{\textit{онтологии} \textit{естественного языка} активно применяются для генерации текстов \textit{естественного языка} на основе некоторой \textit{онтологии} предметной облас
Я не согласна с замечаниями, для введения используется вектор*, значит для понимания смысла уже нужно учитывать и порядок предложений. Не вижу проблемы в таком делении. Можно предложения поменять немного, чтобы воспринимались как какие-то факты

Но если поменять нужно, то окей (но мне не нравится такое)

2024-07-16 10:36 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_natural_languages.tex
> +    \bigskip
Так красиво, не исправляю

2024-07-17 09:05 UTC, MakarenkoAI commented on Contents/part_kb/src/sd_natural_languages.tex
> +                    \end{scnindent}
![image](https://github.com/user-attachments/assets/cce772c8-8ac4-4ad4-96e3-ff05626b31fb)
книга => часть*: книга/стр.25

2024-07-19 15:49 UTC, MksmOrlov requested changes
И надо незакрытые порешать

2024-07-19 15:49 UTC, MksmOrlov commented on Contents/part_kb/src/sd_sem_natural_lang.tex
> +        %тут мы комбинируем смыслы прилагательного и существительного, которые входят в одну именную группу
это весело, но надо убрать

2024-07-22 11:38 UTC, MksmOrlov requested changes

2024-07-22 11:38 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scntext{определение}{\textbf{\textit{адъюнкт}} --- \textit{синтаксическая группа}, являющаяся дочерью (\textit{непосредственно составляющей}) промежуточной проекции и сестрой промежуточной п
адъюнкт

2024-07-22 11:38 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scnheader{комплемент}
спецификатор

2024-07-22 11:38 UTC, MksmOrlov commented on Contents/part_kb/src/sd_syntax_natural_lang.tex
> +        \scneq{{\scnfileimage[30em]{Contents/part_kb/src/images/sd_natural_languages/complement_rule.png}}}
Правила надо связать с самим сущностями

2024-07-26 09:01 UTC, MksmOrlov approved these changes

2024-08-01 15:35 UTC, merged