Fix/translator
ostis-ai/ostis-standard pull request #412
Opened 2024-07-11 17:04 UTC by MakarenkoAI

2024-07-26 09:37 UTC, MksmOrlov requested changes

2024-07-26 09:37 UTC, MksmOrlov commented on Contents/part_kb/src/intro_lang/intro_sc_code_segments/segment_7.tex
> +	\scnheader{$\scnleftsquarebrace$ sc-конструкция $\scnrightsquarebrace$}
я думаю, нужно сделать так, чтобы доллары были внутри тега, чтобы пользователь не писал их здесь. Если так можно

2024-07-26 09:37 UTC, MksmOrlov commented on Contents/part_ps/src/sd_ann.tex
> +    \scntext{пояснение}{\textbf{\textit{формальный нейрон}} --- это основной элемент \textit{искусственной нейронной сети}, применяющий свою \textit{функцию активации} (\scncite{Golovko2017}) к сумме
почему в этом ПРе появилось много текста про нейронки? ты ведь переводила главу, это все уже должно быть

2024-07-26 10:54 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ann.tex
> +    \scntext{пояснение}{\textbf{\textit{формальный нейрон}} --- это основной элемент \textit{искусственной нейронной сети}, применяющий свою \textit{функцию активации} (\scncite{Golovko2017}) к сумме
наверное из-за ребейза что-то лишнее взяла

2024-07-29 08:06 UTC, NikitaZotov approved these changes

2024-07-29 16:01 UTC, MksmOrlov approved these changes

2024-08-01 15:10 UTC, merged