feat(kb): Part 3.4
ostis-ai/ostis-standard pull request #413
Opened 2024-07-17 20:33 UTC by MakarenkoAI

2024-07-21 09:25 UTC, MksmOrlov requested changes
to be continued...

2024-07-22 10:44 UTC, MksmOrlov requested changes

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_syntax_sc_quest_lang.tex
> +
если выделять такую ПрО, то надо хотя бы макс класс объектов исследования указать

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_syntax_sc_quest_lang.tex
> +    \scnheader{Язык вопросов для ostis-систем}
```suggestion
    \scnheader{синтаксис sc-языка вопросов}
```

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang.tex
> +        \scnitem{Язык вопросов для ostis-систем}
странно, что ПрО называется "Предметная область **sc-языка вопросов**", а ключевой знак и дальше в тексте "**Язык вопросов для ostis-систем**". Предлагаю выбрать одно название и его везде использовать. Уточнить предлагаю у авторов раздела, в первую очередь у Никиты и ВВ

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \end{scnhaselementrolelist}
тут должнен быть знак "Денотационная семантика Языка вопросов для ostis-систем"

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \scntext{пояснение}{Между \textit{знаками в рамках заданного вопроса} задается множество связей \textit{отношений}, входящих в состав различных \textit{предметных областей}.}
я бы склеил с предыдущим блоком, понятие то одно и то же

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +                    \scnrelfrom{ответ на вопрос}{\{Железнодорожный район Города Витебск, Октябрьский район Города Витебск, Первомайский район Города Витебск\}}
отступ протерялся
![image](https://github.com/user-attachments/assets/99887f25-8e92-4125-be98-e6c002619400)

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +                    \scnrelfrom{ответ на вопрос}{\{Железнодорожный район Города Витебск, Октябрьский район Города Витебск, Первомайский район Города Витебск\}}
ниже тоже

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \scntext{примечание}{Таким образом, для каждого \textit{вопроса} \textit{пользователя ostis-системы} можно найти класс \textit{вопросов}, на котором можно реализовывать \textit{вывод ответов} на
такое понятие впервые появляется, не принадлежит никакой из ПрО. Надо либо переименовать в вопрос, либо добавить понятие в ПрО и объяснить чем отличается от вопроса

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_operat_sem_sc_quest_lang.tex
> +    \scntext{примечание}{Все \textit{sc-агенты}, выводящие \textit{ответы на} поставленные \textit{вопросы}, формируют \textit{коллектив sc-агентов} --- \textbf{\textit{интерпретатор Языка вопросов д
я бы склеил с блоком выше

2024-07-22 10:44 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_operat_sem_sc_quest_lang.tex
> +            \item информационная потребность \textit{пользователей ostis-системы} может быть выражена в виде \textit{вопросов}, а удовлетворение этой информационной потребности --- в виде \textit{отв
это заключение у онтологии, не у интерпретатора языка вопросов

2024-07-23 15:59 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_sc_quest_lang.tex
> +        \scnitem{Язык вопросов для ostis-систем}
@NikitaZotov, помоги, пожалуйста

2024-07-23 16:04 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \scntext{пояснение}{Между \textit{знаками в рамках заданного вопроса} задается множество связей \textit{отношений}, входящих в состав различных \textit{предметных областей}.}
пояснение здесь не подойдет для определения

2024-07-24 12:57 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang.tex
> +        \scnitem{Язык вопросов для ostis-систем}
![image](https://github.com/user-attachments/assets/0981c2ef-893b-41da-a385-29610844bdb1)
надо везде исправить на такую формулировку

2024-07-24 13:00 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \scntext{пояснение}{Между \textit{знаками в рамках заданного вопроса} задается множество связей \textit{отношений}, входящих в состав различных \textit{предметных областей}.}
я имею ввиду не ссылки склеивать, а теги перенести в предыдущее упоминание "знак в рамках заданного вопроса". Не делать второй scnheader. Это чисто эстетически, для scs необязательно

2024-07-24 13:05 UTC, MksmOrlov requested changes
And unresolved

2024-07-25 15:03 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \end{scnreltolist}
![image](https://github.com/user-attachments/assets/8760ce1b-5feb-4f51-b805-ee3f4dee6e5c)

2024-07-26 08:59 UTC, MksmOrlov commented on Contents/part_ps/src/sd_sc_quest_lang/sd_denot_sem_sc_quest_lang.tex
> +    \end{scnreltolist}
а к чему это?

2024-07-26 08:59 UTC, MksmOrlov approved these changes

2024-08-01 15:33 UTC, merged