feat(kb): part 3.2
ostis-ai/ostis-standard pull request #414
Opened 2024-07-22 11:51 UTC by MakarenkoAI

2024-07-24 12:36 UTC, MksmOrlov requested changes

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Однако значительно более логично и целесообразно описывать \textit{синтаксис} других языков на универсальном \textit{языке представления знаний} --- \textit{SC-коде}. Такой п
"однако" и текст далее относится к предыдущему примечанию. Предлагаю сделать сдвиг вправо для этого примечания

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{\textit{Семантика метода} разъясняет смысл \textit{синтаксических конструкций метода}. Наиболее распространенными методами описания семантики \textit{языков программирования}
```suggestion
    \scntext{примечание}{\textit{семантика метода} разъясняет смысл \textit{синтаксических конструкций метода}. Наиболее распространенными методами описания семантики \textit{языков программирования} являются: денотационной, операционный, аксиоматический, алгебраический. На базе принципов Технологии OSTIS, под семантикой метода будем подразумевать объединение \textit{денотационной} и \textit{операционной семантики метода}.}
```
осторожно везде

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    	\\Отношение \textit{метаметод верификации и оценки качества*} представляет собой класс sc-связок между \textit{sc-связкой}, обозначающей множество \textit{методов}, и sc-узлом, обозначающим мето
это два примечания к соответствующим отношениям, не к классу

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Понятно, что для использования \textit{языка представления методов} следует описать каждую конструкцию языка в отдельности, а также ее применение в совокупности с другими кон
```suggestion
    \scntext{примечание}{Для использования \textit{языка представления методов} следует описать каждую конструкцию языка в отдельности, а также ее применение в совокупности с другими конструкциями. В языке существует множество различных конструкций, точное определение которых необходимо как программисту, применяющему язык, так и разработчику компилятора для этого языка. Программисту эти знания позволяют прогнозировать вычисления, производимые операторами метода. Разработчику описания конструкций необходимы для создания правильной реализации компилятора.}
```
кому понятно?

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Текущее состояние в области проектирования и разработки программного обеспечения говорит о том, что разработчики больше стремятся автоматизировать разработку методов на конкр
Нужно формализовать используя отношение "проблемы текущего состояния"

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Таким образом, одной \textit{Cемантической теории программ} недостаточно. Кроме нее, для перманетного и беспрепятственного проектирования и разработки \textit{методов} различ
```suggestion
    \scntext{примечание}{Одной \textit{Cемантической теории программ} недостаточно. Кроме нее, для перманетного и беспрепятственного проектирования и разработки \textit{методов} различного класса необходимо разрабатывать:
```
каким таким?)

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +	\scnheader{Метасистема OSTIS}
```suggestion
	\scnheader{интеллектуальная система поддержки проектирования и разработки методов}
```

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Потенциальная система должна быть частью общего инструментального средства разработки интеллектуальны компьютерных систем нового поколения --- \textit{Метасистемы OSTIS} ---
вправо

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{\textbf{\textit{легкость чтения метода}} должна способствовать легкому выделению основных понятий каждой части метода без обращения к его спецификации.}
я бы это примечание сделал к понятию "легкость чтения и понимания метода"

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{\textbf{\textit{стоимость метода языка представления методов}} складывается из нескольких составляющих:}
это некруто. Я бы в принципе удалил этот блок, хватит того, что ниже

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scnheader{размер стоимости создания метода $\cup$ размер стоимости тестирования метода $\cup$ размер стоимости использования метода}
можно ли вместо этого использовать "общая стоимость метода"?

2024-07-24 12:36 UTC, MksmOrlov commented on Contents/part_ps/src/sd_programs.tex
> +\scntext{заключение}{Данная предметная область является началом \textit{Семантической теории программ для компьютерных систем нового поколения}. Логичным развитием данной предметной области будут:
это заключение к ПрО и онтологии, а не к сущности теории программ

2024-07-26 07:20 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scnheader{семантика метода $\cup$ синтаксис метода}
с удовольствием ест

2024-07-26 07:27 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Потенциальная система должна быть частью общего инструментального средства разработки интеллектуальны компьютерных систем нового поколения --- \textit{Метасистемы OSTIS} ---
не понимаю что вправо сдвинуть

2024-07-26 08:46 UTC, MksmOrlov commented on Contents/part_ps/src/sd_program_interpreting.tex
> +    \scntext{примечание}{Потенциальная система должна быть частью общего инструментального средства разработки интеллектуальны компьютерных систем нового поколения --- \textit{Метасистемы OSTIS} ---
примечание "каждый компонент должен содержать". Это ведь относится к тому, что описывается с примечании выше

2024-07-26 12:44 UTC, MksmOrlov requested changes

2024-07-26 13:00 UTC, MksmOrlov requested changes

2024-08-01 11:41 UTC, MksmOrlov approved these changes

2024-08-01 15:32 UTC, merged