3.3
ostis-ai/ostis-standard pull request #416
Opened 2024-08-02 12:25 UTC by MakarenkoAI

2024-08-21 18:35 UTC, PetrochukKsenija requested changes
В некоторых частях вставлено несколько абзацев из монограции в один блок текста в стандарте, в основном в старом материале, а не в том, который Аня добавляла. Не знаю, насколько это серьёзно и надо ли сейчас тратить время на исправление, то это выглядит не очень формализовано. @MksmOrlov

2024-08-21 18:35 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_scp_denote_sem.tex
> +%Пример выполнения scp-оператора удаления одноэлементной конструкции (вызов scp-оператора)
а почему комментарий? в монографии к этому пункту есть два изображения и текст в ним

2024-08-22 15:13 UTC, MksmOrlov commented on Contents/part_ps/src/sd_ps.tex
> +		\scnfileitem{Состояние работ англоязычных авторов, посвященных вопросам решения задач в \textit{системах, основанных на знаниях}, и актуальных на момент начала 1990-х годах, отражено в обзорных пуб
Верно. В графах нету выше или ниже

2024-08-26 13:53 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ps.tex
>  \scnheader{решатель задач ostis-системы}
я пока не знаю как правильно формализовать, сделаю когда пойму

2024-08-28 09:31 UTC, MakarenkoAI commented on Contents/part_ps/src/sd_ps.tex
> +\begin{scnsubstruct}
Предлагаю: Классификация машин обработки знаний,  соответствующих одним и тем же фрагментам базы знаний и образующим разные решатели задач

Тут очень длинный хедер, нужно переименовать

2024-09-02 19:16 UTC, MksmOrlov requested changes

2024-09-12 04:48 UTC, PetrochukKsenija requested changes

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\scnfileitem{В качестве основы для построения модели гибридного \textit{решателя задач} предлагается использовать \textit{многоагентный подход}. Данный подход позволяет обеспечить основу для постро
```suggestion
		\scnfileitem{В качестве основы для построения модели гибридного \textit{решателя задач} предлагается использовать \textit{многоагентный подход}. Данный подход позволяет обеспечить основу для построения параллельных асинхронных систем, имеющих распределенную архитектуру, повысить модифицируемость и производительность разработанных \textit{решателей задач}.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\scnfileitem{\textit{решатель задач} (как объединенный, так и \textit{решатель задач} частного вида) предлагается рассматривать как иерархическую систему, состоящую из нескольких взаимосвязанных ур
```suggestion
		\scnfileitem{\textit{решатель задач} (как объединенный, так и \textit{решатель задач} частного вида) предлагается рассматривать как иерархическую систему, состоящую из нескольких взаимосвязанных уровней. Такой подход позволяет обеспечить возможность проектирования, отладки и верификации компонентов на разных уровнях независимо от других уровней, что существенно упрощает задачу построения \textit{решателя задач} за счет снижения накладных расходов.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +			\begin{scnrelfromlist}{включение}
Оформить пункты списка с большой буквы и в конце каждого поставить точку

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\scntext{определение}{принципы обмена сообщениями между агентами --- это принципы, описывающие то, каким образом эти сообщения передаются от \textit{агента} к \textit{агенту}}
```suggestion
		\scntext{определение}{принципы обмена сообщениями между агентами --- это принципы, описывающие то, каким образом эти сообщения передаются от \textit{агента} к \textit{агенту}.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\scntext{определение}{\textit{классификация, семантика и прагматика сообщениями между агентами} --- \textit{смысл} передаваемой информации и цель такого взаимодействия}
```suggestion
		\scntext{определение}{\textit{классификация, семантика и прагматика сообщениями между агентами} --- \textit{смысл} передаваемой информации и цель такого взаимодействия.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\begin{scnrelfromlist}{следствие}
Поставить точки в конце каждого пункта

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +	\begin{scnrelfromlist}{решение проблем}
Точки в конце пунктов

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +	\scnfileitem{В основу решения задач в рамках \textit{распределенного коллектива ostis-систем} предлагается положить идею максимально возможной \uline{унификации} и \uline{конвергенции} принципов реш
```suggestion
	\scnfileitem{В основу решения задач в рамках \textit{распределенного коллектива ostis-систем} предлагается положить идею максимально возможной \uline{унификации} и \uline{конвергенции} принципов решения задач в рамках \textit{индивидуальной ostis-системы} и \textit{распределенного коллектива ostis-систем}. Такой подход обладает следующим важным достоинством: если общие принципы решения задач не зависят от того, какой конкретно набор \textit{ostis-систе}м участвует в решении той или иной задачи, то становится возможным легко переходить от \textit{индивидуальной ostis-системы} к \textit{распределенному коллективу ostis-систем} при ее усложнении без необходимости существенно пересматривать коллектив \textit{агентов}, входящих в состав такой \textit{ostis-системы} и заново продумывать используемый подход к решению задач того или иного класса.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\begin{scnsubdividing}
Точки в конце пунктов

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +	\scnfileitem{Таким образом, можно говорить о фрактальной иерархической структуре распределенного \textit{гибридного решателя задач}, в рамках которой выделяется два варианта иерархии \textit{sc-аген
```suggestion
	\scnfileitem{Таким образом, можно говорить о фрактальной иерархической структуре распределенного \textit{гибридного решателя задач}, в рамках которой выделяется два варианта иерархии \textit{sc-агентов}.}
```

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\begin{scnsubdividing}
точки в конце пунктов

2024-09-12 04:48 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +			\item Разработку формальных критериев для оценки целесообразности или нецелесообразности формирования временных индивидуальных ostis-систем;
```suggestion
			\item Разработку формальных критериев для оценки целесообразности или нецелесообразности формирования временных индивидуальных ostis-систем.
```

2024-09-25 20:14 UTC, PetrochukKsenija requested changes

2024-09-25 20:14 UTC, PetrochukKsenija commented on Contents/part_ps/src/sd_ps.tex
> +		\begin{scnrelfromlist}{следствие}
Каждое следствие с большой буквы и точка в конце

2025-01-06 18:38 UTC, ShunkevichDV approved these changes

2025-01-11 06:27 UTC, merged