Part 4.2
ostis-ai/ostis-standard pull request #420
Opened 2024-08-19 12:21 UTC by PetrochukKsenija

2024-08-19 16:34 UTC, MakarenkoAI requested changes

2024-08-19 16:34 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_natural_lang_interface.tex
> +    \begin{scnrelfromlist}{ключевой знак}
@MksmOrlov, тут вроде через \begin{scnreltolist}{ключевой знак}

2024-08-19 16:34 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_natural_lang_interface.tex
> +    \begin{scnrelfromlist}{ключевое отношение}
здесь не ключевое отношение, а \scnhaselementlist{класс объектов исследования} (и исследуемые отношения)

2024-08-19 16:34 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_natural_lang_interface.tex
> +        \scnitem {методы на основе правил и лингвистических знаний}
тут пробел после \scnitem  
 думаю транслятор не потянет такое

2024-08-19 16:34 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \scntext{примечание}{\textbf{\textit{действие. разрешение контекста}} сводится к сопоставлению каждому варианту его значения соответствующего \textit{контекста}. Выбор производится на основании з
я так и не написала правила для формул
нижнее подчеркивание через  word\underscore{word} и верхний индекс через word\upperscore{word}

2024-08-20 18:00 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +        \scnfileitem{В результате действия перехода от результата синтаксического анализа к потенциально эквивалентным сообщению структурам в базе знаний формируется структура, описывающая возможные
```suggestion
        \scnfileitem{В результате действия перехода от результата синтаксического анализа к потенциально эквивалентным сообщению структурам в базе знаний формируется структура, описывающая возможные варианты смысла сообщения, пример такой структуры в терминах грамматики составляющих приведен на **SCg-текст. Иллюстрация конструкции, описывающей потенциальные смыслы сообщения.** Наличие нескольких таких структур объясняется тем, что в общем случае на этапе синтаксического анализа выполняется генерация нескольких вариантов синтаксической структуры. Выбор корректного значения сообщения будет осуществлен в ходе выполнения последующих действий.}
        тут можно вынести название картинке в отношение смотрите* под текстом
```

2024-08-20 18:04 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \scntext{примечание}{\textbf{\textit{действие. выбор смысла сообщения}} представляет собой выбор из множества вариантов трансляции и соответствующих им \textit{контекстов} одной пары и обозначени
```suggestion
    \scntext{примечание}{\textbf{\textit{действие. выбор смысла сообщения}} представляет собой выбор из множества вариантов трансляции и соответствующих им \textit{контекстов} одной пары и обозначение ее как эквивалентной сообщению конструкции. В простейшем случае, на данном этапе допустимо выполнить выбор в соответствии с рассчитанными на предыдущем этапе для пар потенциально эквивалентных структур и соответствующих им \textit{контекстов} значениями функции \textit{$F\underscore{CTD}(T, C)$} и выбрать пару, для которой оно максимально, однако при необходимости также возможно введение и отдельной функции.}
```

2024-08-20 18:05 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_synthesis.tex
> +    \scnsectionheader{Предметная область и онтология синтеза естественно-языковых сообщений ostis-системы}
в предметной области нужно выделить классы исследуемые, хотя бы несколько

2024-08-20 18:08 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_synthesis.tex
> +    \scntext{примечание}{\textit{Библиотека многократно используемых компонентов} является важнейшим понятием в рамках \textit{Технологии OSTIS}. Библиотека многократно используемых компонентов естес
тут одно предложение потерялось
При необходимости, библиотеку многократно используемых компонентов естественно-языковых интерфейсов можно дополнять знаниями о конкретных естественных языках.

2024-08-21 18:53 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \scntext{примечание}{\textbf{\textit{действие. выбор смысла сообщения}} представляет собой выбор из множества вариантов трансляции и соответствующих им \textit{контекстов} одной пары и обозначени
уже исправила

2024-08-22 15:10 UTC, MksmOrlov requested changes

2024-08-22 15:10 UTC, MksmOrlov commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \scnheader{SCg-текст. Иллюстрация конструкции, описывающей потенциальные смыслы сообщения}
смысл сообщения => пример*: SCg-текст. Иллюстрация конструкции, описывающей потенциальные смыслы сообщения

2024-08-22 15:10 UTC, MksmOrlov commented on Contents/part_ui/src/sd_process_message_synthesis.tex
> +    \begin{scnrelfromvector}{этапы процесса разработки естественно-языкового интерфейса ostis-систем}
```suggestion
    \begin{scnrelfromvector}{этапы}
```

2024-08-22 15:12 UTC, MksmOrlov commented on Contents/part_ui/src/sd_natural_lang_interface.tex
> +    \begin{scnrelfromlist}{ключевой знак}
да

2024-08-26 08:39 UTC, MakarenkoAI approved these changes

2024-08-26 08:39 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_synthesis.tex
> +    \scnsectionheader{Предметная область синтеза естественно-языковых сообщений ostis-системы}
```suggestion
    \scnheader{Предметная область синтеза естественно-языковых сообщений ostis-системы}
```

2024-08-26 08:39 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \scntext{примечание}{\textbf{\textit{действие. выбор смысла сообщения}} представляет собой выбор из множества вариантов трансляции и соответствующих им \textit{контекстов} одной пары и обозначени
у меня почему-то все равно не видно

2024-08-28 15:55 UTC, MksmOrlov requested changes

2024-08-28 15:55 UTC, MksmOrlov commented on Contents/part_ui/src/sd_natural_lang_interface.tex
> +    \scnrelto{пример}{Абстрактный sc-агент}
А давай удалим этот фрагмент и никому не скажем. Мне кажется, он лишний и ничего не говорит полезного

2024-08-28 15:55 UTC, MksmOrlov commented on Contents/part_ui/src/sd_process_message_synthesis.tex
> +    \begin{scnhaselementrolelist}{класс объектов исследования}
Нужно добавить максимальный класс объектов исследования

2024-08-28 15:55 UTC, MksmOrlov commented on Contents/part_ui/src/sd_process_message_understanding.tex
> +    \begin{scnhaselementrolelist}{класс объектов исследования}
Максимальный тоже

2024-09-02 18:55 UTC, MksmOrlov approved these changes

2024-09-02 18:58 UTC, merged