fear(kb): part 4.3
ostis-ai/ostis-standard pull request #422
Opened 2024-09-03 08:43 UTC by MakarenkoAI

2024-09-03 10:41 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_ui_voice.tex
> +\begin{scnrelfromlist}{подраздел}
```suggestion
\begin{scnrelfromlist}{контакенация сегментов}
```

2024-09-17 22:33 UTC, PetrochukKsenija requested changes

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scntext{примечание}{Подавляющее большинство высокоуровневых речевых моделей, используемых на практике, являются проблемно-ориентированными и могут применяться только для решения одной, узкоспециализ
ссылка на главу 3.1

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scntext{преимущество}{Основным преимуществом модели является раздельное описание сигнала в виде огибающей спектра и сигнала возбуждения. Огибающая спектра определяет фонетику произносимого звука и х
```suggestion
\scntext{преимущество}{Раздельное описание сигнала в виде огибающей спектра и сигнала возбуждения. Огибающая спектра определяет фонетику произносимого звука и характеризует состояние речевого тракта, в то время как сигнал возбуждения характеризует состояние голосовых связок и высоту (интонацию) вокализованных звуков.}
```

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scntext{преимущество}{Преимуществом линейного предсказания является низкая вычислительная сложность.}
```suggestion
\scntext{преимущество}{Низкая вычислительная сложность.} 
```

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scnheader{Моделирование речевого сигнала на основе линейного предсказания}
предлагаю тут два примущества оформить списком или множеством

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scnfileitem{К ограничениям предлагаемого подхода можно отнести следующие основные факторы. Очевидно, что для достижения поставленной цели и реализации задач по формализации любой предметной области,
Предлагаю в этом блоке текста явно выделить два подпункта (\item), чтобы было проще для восприятия

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scntext{преимущество}{Преимуществом является теоретическая возможность моделирования вокализованных звуков в виде непрерывных функций с изменяющимися параметрами, что позволяет получить эффективное
```suggestion
\scntext{преимущество}{Теоретическая возможность моделирования вокализованных звуков в виде непрерывных функций с изменяющимися параметрами, что позволяет получить эффективное описание процесса фонации и избежать наложения смежных фрагментов, разрыва фаз при синтезе речи.}
```

2024-09-17 22:33 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scntext{недостаток}{Недостатком модели является высокая сложность алгоритмов анализа и синтеза, обусловленная нестационарностью речевого сигнала.}
```suggestion
\scntext{недостаток}{Высокая сложность алгоритмов анализа и синтеза, обусловленная нестационарностью речевого сигнала.} 
```

2024-09-18 18:10 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_ui_voice.tex
> +	\scnfileitem{Для разработки аудиоинтерфейсов предлагается прибегнуть к подходу на основе принципов, лежащих в основе \scnqqi{Стандарта открытой технологии онтологического проектирования, производств
не, Максим говорил, что на самого себя ссылаться не обязательно

2024-09-18 18:12 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_ui_voice.tex
> +		    \scnfileitem{В качестве технологической основы для реализации предлагаемого подхода будет использоваться Технология OSTIS, соответственно подсистема аудиоинтерфейса будет строиться как \textit{
@NikitaZotov

2024-09-18 18:25 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scnfileitem{К ограничениям предлагаемого подхода можно отнести следующие основные факторы. Очевидно, что для достижения поставленной цели и реализации задач по формализации любой предметной области,
Что-то сделала, но мб неправильно тебя поняла

2024-09-23 04:37 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scnfileitem{К ограничениям предлагаемого подхода можно отнести следующие основные факторы. Очевидно, что для достижения поставленной цели и реализации задач по формализации любой предметной области,
я имелла виду выделить вот так пункты
"К ограничениям предлагаемого подхода можно отнести следующие основные факторы. Очевидно, что для достижения поставленной цели и реализации задач по формализации любой предметной области, в том числе и аудиоинтерфейсов, требуется в первую очередь большое количество источников знаний для их пополнения. Для преодоления данной проблемы требуется:
- привлечение большого количества экспертов, обладающих соответствующими компетенциями и знаниями в предметной области
- разработка механизмов надежного автоматического извлечения этих знаний из имеющихся источников."

2024-09-23 04:52 UTC, PetrochukKsenija approved these changes

2024-09-23 04:52 UTC, PetrochukKsenija commented on Contents/part_ui/src/sd_ui_voice.tex
> +        \scntext{примечание}{Классы выделены в зависимости от способа математического описания обрабатываемого сигнала в ostis-системе}
```suggestion
        \scntext{примечание}{Классы выделены в зависимости от способа математического описания обрабатываемого сигнала в ostis-системе.}
```

2024-10-03 12:06 UTC, MakarenkoAI commented on Contents/part_ui/src/sd_ui_voice.tex
> +\scnfileitem{К ограничениям предлагаемого подхода можно отнести следующие основные факторы. Очевидно, что для достижения поставленной цели и реализации задач по формализации любой предметной области,
Думаю сейчас тоже хорошо

2024-10-17 08:12 UTC, merged